### ISSUE TITLE
Can you add an announcements banner to the homepage?

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#1]
Marissa from Oberlin will be doing a public history event on the 1910 census in August and asked if you could add a link on the homepage.  Knowing all the sites are similar and that there would be other reasons for this, like announcing upcoming transcription sessions, I'm wondering if you could add a banner for announcements (including links) that could be toggled on or off by the admins for each site?

**Comment by dfurber** [comment]
See the Settings page, Announcement Banner toward the bottom.
