### ISSUE TITLE
Addition of satellite view to miniForge?

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#102]
I have no idea how hard this is to do or if its worth it but one of the testing partners said she was using Google satellite view to help her place buildings that had been recently demolished. It's possible that the outline view might be good enough if this is a lot of extra work.

**Comment by dfurber** [comment]
Sure, why not

**Comment by EveSnyder** [comment]
I think that is accessed by clicking on the option for no historic map but when I do that the miniForge disappears entirely.
