### ISSUE TITLE
person records results page

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#105]
On the person records results page many person records are missing birth year (even though the census records have an age), and place of birth.

**Comment by dfurber** [comment]
Looks like the babies, who got skipped because they had an age of 0, which the system interpreted as being left blank. Now I'll count them as babies, and re-run the thing that fills in the people's DOB and POB.

**Comment by PatientRowan** [comment]
Are you sure it’s just babies?  If you look at just the top of the list, of the Aagards, the parents Andrew and Nancy Aagard are 29 and 26, and their children Andrew, Frances and John are 3, 7 and 5.  Yet none of them have years of birth filled in.

**Comment by dfurber** [comment]
In my local version of the database, it’s just babies…

**Comment by PatientRowan** [comment]
Local version?  Ominous!  I do love hearing more about how many moving parts are involved!  Thank you for letting me ooh and aah as I learn.  I’ll be sedate soon, I promise.
This is what the top of the list looks like to Eve and me:
![D91EC037-CC3B-43A9-8C93-9502E8F19F6E](https://user-images.githubusercontent.com/114665933/193481236-8bc80076-d716-46ba-8d62-8d3ec070c286.png)

**Comment by dfurber** [comment]
I don't use the actual database for testing. Instead I periodically grab a copy of it. Right now I'm running the script that is updating the POB and birth year. It just hasn't gotten to the end yet.

**Comment by PatientRowan** [comment]
And you hold another copy that holds the “before” version of the tests in case something goes tragically wrong?
Can I ask—as for the version that Eve and I are seeing, which you are updating, is it possible that you previously made some changes that didn’t get pushed out?

**Comment by PatientRowan** [comment]
Person Record index is BEAUTIFUL!  Thank you!

**Comment by PatientRowan** [comment]
This morning, I am reviewing census records and creating person records on the fly.  I’m noticing that the person records lack the instantaneous calculation of the birth year:
![78065E4B-0E61-497C-87E4-23DF7F1C841B](https://user-images.githubusercontent.com/114665933/193584924-4bc419d5-258f-4a39-9b08-e09c05ba8585.png)
Which is fine, as long as we remember to take run them through that step later, regularly.
