### ISSUE TITLE
person record-merge fails

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#106]
Tried to merge two person records, the deprecated person record was deleted but the individual census record that was attached to that deprecated record was not actually merged into the retained person record.

**Comment by PatientRowan** [comment]
Newbie here; forgive me for asking, but what does “not published yet” mean?  Eve and I should not try it out again until it is published, right?

**Comment by dfurber** [comment]
It means, I’ve fixed the issue on my computer where I’m working on it, but haven’t pushed it to the servers yet.

**Comment by dfurber** [comment]
I just added it as a label to keep track of the issues that’ll be fixed when I deploy the current code.

**Comment by dfurber** [comment]
Sorry, first and last time I'll try "reply directly to this email" on a github comment.
