### ISSUE TITLE
person results page displays pob incorrectly as original i.e. "Turk as Syrian" and "Syria Sado"

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#107]
On person results page the Pob for some people is displaying with what was originally inputted for the 1910 census i.e. Abbott, Catherine 2579 pob "Turk as Syrian" but when you open her 1910 census record it has been updated to pob "Turkey, Asia" as per census instructions. 
Also see Abbott, Catherine 26229 pob "Syria Sado" which was later updated to pob Syria

**Comment by dfurber** [comment]
Must have been copied over to the person record before the cleanup. I'm changing it so that if the pob or birth year are estimated, then it'll recalculate them when you save the person record.
