### ISSUE TITLE
“View | View” mixing identities?

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#108]
Puzzled by the display in the Person Records index that looks like twinned “View | View.”  
Filter on Last Name Flynn and First Name John.
There’s more than one identity smooshed in these search results, but I am in particular asking about the results that have two “View | View” for one census year.
Flynn, John Jr, age 1 year old in 1900, lives at 610 Utica St and has parents John and Minnie Flynn.
Flynn, John C, also age 1 year old in 1900, lives at 1006 W State St and has parents John and Bridget Flynn.
    **But both these identities have only the one Person Record, 15025.
    What specifically is “View | View” flagging to  #us?  Does it always mean that two separate identities are getting smooshed into one Person Record?
![05B0C29A-B262-44B7-83FC-EE06C20E98B8](https://user-images.githubusercontent.com/114665933/193027571-24b58734-69f3-4edf-b531-04bd084d0118.png)

**Comment by dfurber** [comment]
View | View is flagging that that year has 2 records for the same person. You should identify the one who doesn't belong, remove them from the person record, and create a new one for them.

**Comment by dfurber** [comment]
You should split off the one who doesn't belong.

**Comment by PatientRowan** [comment]
Yes, this makes sense, thank you.  We may want to periodically run a harvest of View-Views to see if any new ones have crept in.

**Comment by dfurber** [comment]
I think that once you harvest the current crop, that SHOULD be it. I think that because I turned off the automatic creation of census records in favor of making the "impersonation" part of the review process. That's because if it isn't reviewed manually, it's gonna gradually degrade the people records without you knowing where without doing a big audit. Easier to audit now and then fill the pool intentionally.

**Comment by PatientRowan** [comment]
I had to think through what you said slowly but yes, I understand and you’re surely right.  I am a bit fearful of the amount of work heaping up on the the reviewer(s)’ shoulders.  I am currently trying to impersonate the names as I review, and I’m not finding it a breeze.  But that is perhaps a sign that we shouldn’t ask the program to do it.
