### ISSUE TITLE
Duplicate Detection not working?

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#110]
At the 9/17/22 transcription session, two different teams of transcribers got mixed up and input the same persons on the same sheet in the same 2-hour period.  All of the persons that are listed below on HistoryForge ED 23, Sheet 6, are true duplicates.  I intend to deleted them when you’ve had a chance to look at them, and then transcribe the real ED 23, Sheet 6.  
How did all these persons go in without being rejected as duplicates?  (One family is Lloyd with one transcriber, Lloyde with another—that one makes sense, of course).  
 ** Is it possible that duplicate detection was affected when automatic merge/person record generation got turned off?

![245ADC0D-648A-436F-94B6-A2F8DAA520CD](https://user-images.githubusercontent.com/114665933/193035903-abac517f-b2f9-4250-b665-5acb6131c889.jpeg)

**Comment by PatientRowan** [comment]
In the 10/1 transcription session, I overheard two transcribers talking about how they’d had a lot of people flagged as duplicates and had to cope with getting their records in.  I suspect now that this was a one-time incident with the program working properly and humans defeating it.  I have not had the nerve to try to deliberately create a duplicate to test this proposition.

**Comment by dfurber** [comment]
That's interesting. You've helped me realize that it's not the address and name I want to hit for duplicate prevention, but census scope.

**Comment by PatientRowan** [comment]
They had their sheet number wrong, so the census scope wasn’t duplicated in their case, just the name/address match.

**Comment by dfurber** [comment]
Then maybe both?

**Comment by dfurber** [comment]
Making it so that we first match on census scope (locality/ward/enum/sheet/side/line), then locality/street number/street name/last name/first name/age.

**Comment by dfurber** [comment]
Please reopen the issue if the changes I made don't seem to fix it.
