### ISSUE TITLE
Create Person does not show birth year instantaneously

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#112]
I am using the Create New Person Record on reviewing census records.  When I hit it, the Person Record created does not show the birth year in the About area.  When I edit, there is not date in the Birth Year box.  But if I make no changes, and merely Save the unchanged record, the Birth Year magically appears.
Before picture:
![0114DEB7-089A-4D39-8542-4F28F9625651](https://user-images.githubusercontent.com/114665933/194061827-7bc63afa-a6f7-4a31-be28-5b3499841ac0.jpeg)
The edit screen:
![2A7CBA11-1690-4A76-8AD6-02AE3BB54DF3](https://user-images.githubusercontent.com/114665933/194061888-6ae1fd83-fa3d-4a45-83b8-54ba194330da.jpeg)
After the Save:
![8B530576-51CC-4ECD-9D24-0FAB3CA65C1C](https://user-images.githubusercontent.com/114665933/194061929-921c8c8c-9491-46b5-ad22-41cf8b538c52.jpeg)

**Comment by dfurber** [comment]
Good catch. I fixed it going forward.

**Comment by PatientRowan** [comment]
Thank you!  And just to check—not trying to be annoying—you can run a catch-up sweep too?
![FD79B500-0E42-4534-BB78-EAB94B547031](https://user-images.githubusercontent.com/114665933/194782428-5867d782-b647-4286-b72e-a64923270814.png)

**Comment by PatientRowan** [comment]
Putting the birth year column in order using the up/down arrows also revealed (new to me) the number of  birth years that are being styled as three digits such as 901, 902, 911.  I might have to do something about them sometime.

**Comment by dfurber** [comment]
Doh, good find. Separate issue, but I can fix that. Some years have an "if you don't know put 999". So I need to filter out ages above, say, 150, before calculating a birth year in the middle ages.

**Comment by PatientRowan** [comment]
For housekeeping, should I create a separate issue for you?  This would not be urgent.

**Comment by dfurber** [comment]
No need. The fix is on the way. It also revealed that when the person's only census record has the age of 999, then the person record's birth year will be blank. That seems better than 901 though.
