### ISSUE TITLE
1950 Serial #s sometimes concatenate across EDs

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#113]
[This is posted by Patient Rowan on behalf of Caroline Arms, who noticed the problem and documented it as below.  I don’t have a sense of how common it is—just that I too have occasionally had an uneasy feeling that a particular household is too big.  I have not seen it in the City of Ithaca to my knowledge].

https://www.historyforge.net/census/1950/6420
shows a problem with Other Family Members.

The list includes the households with serial # 146 from ENUM 1 and ENUM 2 for Caroline. If I click on Warren A Blye, that display shows the same problem.

See screenshots:
![955740F8-5872-47BE-8CAD-F709C2DB881B](https://user-images.githubusercontent.com/114665933/194782938-a3a843e1-7518-49ac-9c75-fe8dbb49381a.png)

![72B04019-D9A3-4CBC-98B0-F65D44A68F08](https://user-images.githubusercontent.com/114665933/194782945-80fb66e5-033e-47f4-94b1-ee4876435dc3.png)

I see the same problem for serial # 145 as well.  See https://www.historyforge.net/census/1950/6418

**Comment by dfurber** [comment]
Also need to scope the query to same enum dist. Fix is on the way up now.

**Comment by dfurber** [comment]
BTW love the detailed explanation, the screen shots, and the URL where I can see the probelm.

**Comment by PatientRowan** [comment]
I will be sure to let Caroline know.  It is a pleasure to work with you.
