### ISSUE TITLE
Add metadata for Person Records

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#114]
Eve and I were exploring person records today. We were already wishing we had some metadata on the person records similar to the info on census and building records.
Could you show us the date the record was created, whether it was created by a machine or human, matched by machine or human or merge, and what the changes were and who made them?  Roughly.  Anything helps, but anything that’s too hard for you to extract or display, we can make do without.

**Comment by dfurber** [comment]
On one hand, person record isn't quite as sophisticated yet as census record, in that it doesn't get reviewed, and doesn't track who created it, at least on the record itself.

On the other hand, it's always been versioned, which means I can easily pop the same "Change History" block onto the person page. That will give you the goods on the person record attributes. Unfortunately it won't say who connected which census records when, but you with a little clicking through to the census record, you can get it from there.

**Comment by PatientRowan** [comment]
Your change history oughta do it.  Thank you.
