### ISSUE TITLE
Add new user role

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#115]
We need something short of “Administrator” for users who have permission to work with Person Records but can’t “do everything.”  Could you add a new role called something like Person Record Editor?

**Comment by EveSnyder** [comment]
I concur, how about giving them the capacity to create and edit person records (similar to editor for census records). I just enabled private the person records under settings such that now people logged in can view the person records but can't edit them. It would be helpful to let a limited number of people edit the person records without giving them all the permissions of the administrator role.

**Comment by dfurber** [comment]
Makes sense. I just added the "Person Record Editor" role.
