### ISSUE TITLE
Add columns for Race and Place of Birth on Person Record

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#117]
Eve and I think this would be useful for us—is it possible, or too crowded?  When we are comparing two person records for a possible merge, seeing the Race and Place of Birth for each census year at a glance would be helpful. We’ve had somebody change race in between census years (probably just enumerator error), and persons with the same name born in Syria versus New York.
Something like this?  Is there room?  You can say no.
![267756FA-C196-4AF7-B193-DDAFE9CD58B1](https://user-images.githubusercontent.com/114665933/194931107-c05febc4-e182-46ad-a6bc-43c0f289c2b0.jpeg)

**Comment by PatientRowan** [comment]
Eve and I thought that we needed the extra columns of info when we first started working with the records.  After working with them for a couple of weeks now, I’m not sure that they’re really necessary.  I have got more bold about adding “Description” notes that flag inconsistencies in those data points if they are troubling.  Eve, how do you feel about this?

**Comment by dfurber** [comment]
It wasn't a heavy lift, so I'd only remove them if they get in the way.

**Comment by PatientRowan** [comment]
I worked on my little first-name-Mrs. project this evening after you made the change, and I must say, I started relying on the POB display right away without even realizing I was doing it.  Really helpful.  I like it.  Thank you.
