### ISSUE TITLE
Add Title element to Person Name header

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#123]
Working on a Mrs. M.S. Badger.  Today we would parse her name as Badger, M. S. [title] Mrs, but this is currently impossible in the header on the Person record:
![1E37C99A-4DCB-41C1-A056-10FFD94D766C](https://user-images.githubusercontent.com/114665933/196721543-97f2f265-0f0e-4d4e-91d6-8522dd3c2432.jpeg)

**Comment by PatientRowan** [comment]
When Title is added, I’ll go through the database with a “First Name Contains Mrs” search and parse them out.  The other day I moved about 70 Jr from the first name area to the Suffix area, and a smaller number of Sr, III, IV, Second and Third.  When Title is available I’ll search for Mrs, Dr, and Rev.  I’m sure there are others but that ought to hit the main ones.

**Comment by dfurber** [comment]
Prefix = Title

**Comment by PatientRowan** [comment]
Duh!  Sorry I bothered you with this!
