### ISSUE TITLE
Index Variant Names in the Person Record index

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#125]
Eve and I are aware this is a big ask.  We’re not making it casually.  Could we start to talk about it?  Both HF workers and eventually the general public need a way to search on the “wrong” name and get led to the “right” name.

The most obvious use case is maiden names.  Ithaca girl meets Ithaca boy and her name changes to his:

![84A750EE-B3D2-495E-A776-711CC7DE3D21](https://user-images.githubusercontent.com/114665933/197026328-f64560d9-3088-4306-842e-98c90039391d.png)

But there are numerous other kinds of variant names that users could legitimately be searching on:
•Mis-spellings on the censuses themselves, that have perhaps entered FamilySearch/Ancestry indexes
•Variant spellings (De Camp/DeCamp) and usages (Susan/Susie) between census years, which currently display on the Person records but do not index
•Spellings and usages from other sources such as the city directories and Find-a-Grave

The Person records could continue to display as they do now, but when you hit the Edit button, maybe there could be room for variant names—the names that you already have from the census records, and room for HF workers to add more names that they discover?  Sort of like the space for variant addresses on the Building records:

![219A7D0C-D40E-48B5-B724-602ED5D27FE3](https://user-images.githubusercontent.com/114665933/197030092-8ae3a41a-113a-400d-90de-60f8f3361bfa.jpeg)

**Comment by PatientRowan** [comment]
Here are some ideas that I’m carrying around as possible sketches for a HistoryForge person record index.  I like to use Muammar Qaddafi as an example because he’s on the outer edge of a person who has lots of name variants.  Nothing like this bad would happen in HistoryForge.  But look how nicely he can be tied together!

This is his VIAF, the Virtual International Authority File:
![7A9B1297-4251-449E-B070-7348B1F4CD77](https://user-images.githubusercontent.com/114665933/197030987-7b5bc4f5-192f-438c-a225-4f647506ab82.png)

Check out all the variants on the Library of Congress’s authority record here: https://id.loc.gov/authorities/names/n81068638.html
Small portion of that record:
![4FE06A0D-2D08-428B-BD57-8440433142C2](https://user-images.githubusercontent.com/114665933/197031247-1cee06f8-2ff1-457c-8287-e5f79c107853.jpeg)


I really like the arrangement below from OCLC’s searchFAST below because the authorized heading (that HF Person records put at the top of the screen, and which is fixed, while the census years can vary)—this index’s authorized headings are **bold** and the variant names are greyed out but clickable and lead you to the authorized form.  Also, it’s fuzzy match searching so that typing just Muam puts you in the neighborhood of the entry element of his last name Qaddafi:

![4CCE46A9-AF9D-4A86-9829-AB1EDD44DF0A](https://user-images.githubusercontent.com/114665933/197031551-e9a3c252-553f-45ca-8a5a-da07ec1e2461.png)

**Comment by dfurber** [comment]
"Do it like building address" is a great idea.

**Comment by PatientRowan** [comment]
From Twitter:
![E0342DB0-0C44-4B2E-9732-BBC0095BB11B](https://user-images.githubusercontent.com/114665933/219139273-74547b07-a6e9-46ad-80f8-0a15c6906564.jpeg)

**Comment by PatientRowan** [comment]
I apologize if I'm being annoying by harping on this issue all the time.  It's not something you can just dash off.  But I did want you to have the opportunity to see the documentation I am writing around what we imagine(!) the future of person records will be.  @EveSnyder thinks this attached document is way more than you want to know about, and she's probably right but I believe in communicating ...
[Name Variants Draft.docx](https://github.com/historyforge/historyforge/files/10861991/Name.Variants.Draft.docx)

**Comment by PatientRowan** [comment]
I love the new Find a Person off the home page (#264). It was time!
    I know we can’t have Name Variants yet, that’s going to be complicated.  I started wondering, though—what would you think about not offering name variants off the home page (unlike the way you offer building variants off the home page, #152)?  Instead, if their search has no hits, giving users a message to use “All People” for a more advanced search?  And offering name variants there?

**Comment by PatientRowan** [comment]
DAVE this is so exciting!  I see your developments on person records this morning.  I’m still playing around with figuring it out.  Happy holidays !!

**Comment by PatientRowan** [comment]
Can it be affecting the matching algorithm?  It’s weird, exact matches are being offered way far away from each other instead of the top match.  Example
1950 Hart, Van B is offered a match on 1940 Hart, Van B but is the 11th match offered.  His wife, Helen, isn’t offered a match at all.  No age problems

**Comment by PatientRowan** [comment]
Nice!
![IMG_0549](https://github.com/historyforge/historyforge/assets/114665933/af330a2d-a056-4a00-9f25-96f080230a44)

**Comment by PatientRowan** [comment]
I’m not so sure about this … I expected the variant to interfile on Beers, with click-through to Sampson:
![IMG_0550](https://github.com/historyforge/historyforge/assets/114665933/7b7bbd13-7de0-4bbf-9361-14b009500f6e)

**Comment by dfurber** [comment]
I just fixed the person matcher. How is it doing now?

**Comment by PatientRowan** [comment]
I hate putting off thrills, but please give me another day to do a sheet and play with it some more.

**Comment by PatientRowan** [comment]
No luck this morning.  It’s slow, timing out, acting like I shouldn’t be in the system at all.  It’s a holiday for all of us.  I’m going to do other fun things and check in again tomorrow.

**Comment by PatientRowan** [comment]
Isn’t this just the greatest?!
