### ISSUE TITLE
Search Person in the public interface

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#127]
I was playing around with the Search Person feature in the public-facing interface.  I love it, and I’m also never sure how it works.  It’s pulling from the Name as entered on the individual’s census record for each census year, right?  Ultimately, do you envisage using the Person Record instead?
    Here’s a straightforward example of a person who will display better if we can pull from her Person Record, as her usage varies.  (Not to mention that she is also a “Miriam” in some Ithaca city directories, if I recall correctly—yet another variant).
![E379504B-3C42-40DA-8248-854A694F3262](https://user-images.githubusercontent.com/114665933/197395677-50b87eee-850c-442d-b508-ec68b52ac447.jpeg)
![06074BE3-D67B-425E-A695-35F3AAC51B93](https://user-images.githubusercontent.com/114665933/197395679-8ee47cc2-91fe-49bd-b2ee-d550dbf6d6e9.jpeg)
Her husband, old Ebenezer Miller, a Civil War veteran, can be hard to find in the pull-down menu.  I could swear that some days I find him by typing in “Ebenezer,” but today I could only find him by searching “B Miller”:
![EBDB8B5A-2F8A-48E5-A39B-10F5217D640C](https://user-images.githubusercontent.com/114665933/197395736-744bf05a-1f4f-4ec8-a66a-267f1e5458fd.jpeg)
   Do you know where the rest of old Mr. Miller is?  The record above is from the 1910 census, but he was alive and present in the 1920 and 1930 censuses as well.  His usage varied, however: sometimes he was Ebenezer Miller and sometimes he used his middle initial B.  His person record unites him across census years.

**Comment by dfurber** [comment]
I agree with you 100% however the person record concept was far from ripe when I did that, so made it pull from census records instead. In looking at it, I did notice that it might not have been updating the index for awhile, so fixing that now.

**Comment by PatientRowan** [comment]
This is so exciting.  Using the person record index in the staff mode, I keep asking myself how bad it would be to offer it to the public.  I mean, we have an awful lot of duplicate persons in the index, and a small number of horrendous snarl-ups.  But I think it will end up being a huge improvement!  Users will still end up having to do some hunting around of their own—we will not resolve all the identity problems—but that is always going to be true, and they will have a much better entry point into exploring by searches on names.
