### ISSUE TITLE
1950 Families "housed" but not listed in the building record

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#128]
Charles Chapman and family and Kenneth Short and family n the 1950 census were housed in 119 Third St Ithaca (this is a new building I just created to differentiate it from a previous building at this address) but are not listed as 1950 residents in this building.
Record for Chapman-https://tompkins.historyforge.net/census/1950/7568
Record for Short-https://tompkins.historyforge.net/census/1950/7571
Record for 119 Third St-https://tompkins.historyforge.net/buildings/8020
I was able to move people from the 1940 census into this building but not these families (who were both just transcribed).

**Comment by PatientRowan** [comment]
I too have been noticing this problem.  See for example 606 S Plain St, which has 3 people from the 1950 census, but none of them show up on the building record.

**Comment by dfurber** [comment]
Do you mean this building? https://tompkins.historyforge.net/buildings/4445
I see 3 people for 1950.

**Comment by PatientRowan** [comment]
Apologies for the delay in getting back to you, I have been down with covid.  I see the 1950 family too … now.  I didn’t see them when I reported it.  I love it when things fix themselves.  I’ll keep an eye out for another occurrence, which hopefully won’t happen.
