### ISSUE TITLE
View | View enhancement

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#132]
Most of the View | View situations we run across seem to be situations where we need to tease apart two different persons who have been matched together on one Person Record.
     However, there are legitimately a few persons who have been enumerated twice within one census year at different locations.  For example, the young soldier Raymond Bewsher has been enumerated at his mother’s house https://tompkins.historyforge.net/census/1920/7939 and at barracks on the Cornell campus https://tompkins.historyforge.net/census/1920/16887
     Or the Black servant Janie Bibbie who has been enumerated at her white employer’s house https://tompkins.historyforge.net/census/1930/11387 at her lodging https://tompkins.historyforge.net/census/1930/12419
     In these cases, instead of splitting them apart onto two separate records, I have kept them as View | Views and put notes on each census record “Same person enumerated twice; see [other HF record].”
      The Person Record, however, only displays and links to ONE of the person’s addresses.  It’s suppressing discovery of a large part of the person’s story.  It’s confusing for HF workers, but they have the tools to figure it out.  It will be more serious for the general public when their Person search hooks into the Person Record index.
      Could you do something like this to link over to BOTH dwellings?
![8D2AA830-99CB-402F-9B42-50599732C91E](https://user-images.githubusercontent.com/114665933/199956185-2eaca058-7cfe-46df-8590-1f607b0f0118.jpeg)

**Comment by dfurber** [comment]
The issue was something else actually. It was always intended that a person record would connect to one and only one record per census. Then we hit the Bibbie problem. So I made it possible to add multiple records for a year to a person. But the person record itself still only knew about the one.

I've adjusted it to be aware of the many, even though that is the exception rather than the rule. So you should now see two 1930 rows on Bibbie.

Please close this issue if you are satisfied with the outcome.

**Comment by PatientRowan** [comment]
Yes, I love it, it’s beautiful.  I’m posting it below for Eve and closing it:
![645FC438-C0C5-4977-B657-3F94DE2246DD](https://user-images.githubusercontent.com/114665933/201547442-097dac95-381f-41ce-bb07-bd665911a479.png)

**Comment by EveSnyder** [comment]
Ah, excellent and much appreciated. Though there might have been an unintended consequence- I tried to merge a few different person records and got an error message each time.

**Comment by dfurber** [comment]
There was indeed a casualty, and I just sent in the medics.
