### ISSUE TITLE
“Null” in building drop-down + Random Localities Missing

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#133]
Posting at Eve’s request.  I was puzzled and Eve figured it out, but we still wanted to ask.  I was fixing a person who lived at 717 N Cayuga St for the 1900 census.  He wasn’t housed, so I tried to house him:
![162AC3BB-12DF-4BE1-B500-71E3FFDD0D85](https://user-images.githubusercontent.com/114665933/200401949-3fd12f05-47f8-4d2b-aa23-f99466810d97.jpeg)
Eve explains:
“I checked the building records and the problem was that there are two buildings at that address. One was built in 1919 with an as of date of 1919 (which was likely the "null" since the as of date means the system shouldn't pull that building record up in the dropdown for a census record from 1900). The other was the correct option but for some reason it didn't have a locality selected—I've been seeing this more lately and I don't know why. Once I noticed that I added the locality and saved the record. I was then able to go in and house Michael and Mary Black at the correct address. The building dropdown [then] had 717 N Cayuga (the correct one) though it was still followed by the record listed as null.”
•Do you have any idea what’s up with localities missing?
 •Is it better to display null—to flag the fact that the building has a chronology problem—or should we let transcribers house any address if it is used on the census?

**Comment by dfurber** [comment]
I think it shows null because the address displayed in the drop down is "as of" the census record year, but the query itself isn't filtering to buildings "as of" that year. 

Also, I noticed that locality was optional on building, for legacy reasons that no longer apply since we've gone all in with them. Unfortunately it was possible to create a building manually without entering a locality, and now there are 734 of them.

**Comment by PatientRowan** [comment]
I have not worked much with Building records but adding a locality to 734 of them sounds like a doable project.

**Comment by dfurber** [comment]
So, I decided that if the "city" field was "Ithaca" it probably belonged in the City of Ithaca and that took care of most of them. I manually updated the remaining handful.

**Comment by dfurber** [comment]
Now that buildings have localities, and locality is required, and the building dropdown will only show buildings existing at that time, you should be good to go. Please verify and close this issue or comment as appropriate.

**Comment by PatientRowan** [comment]
You sweetheart.

**Comment by PatientRowan** [comment]
I will talk to Eve tomorrow since she understands this better than me, and expect to close it then.

**Comment by PatientRowan** [comment]
Sorry not to have closed it like I said I would.  Eve sounded like she is satisfied, but as I don’t understand all the ramifications, I’m leaving it to her to close when the conference is over.
