### ISSUE TITLE
Please set up new installation for Walnut Hills Historical Society in Cincinnati OH

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#134]
We got approved by the NEH to upgrade Walnut Hills to be a quasi member of the first cohort due tot heir previous census mapping project experience. They are ready to start whenever you can get the installation going and I can get the documentation updated and to them. Could you please set up their installation? Is there anything you need from them to do this? Photos of people, buildings, etc.?

**Comment by PatientRowan** [comment]
Housekeeping—can we close this one?
