### ISSUE TITLE
Person records are not showing birth year estimate

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#135]
For the person records I created today, Monday, Nov. 14, I notice that some of them don’t show the estimate of the birth year.  I think you’re better at gaining an overview of this problem than I, so I did not attempt to systematically determine when it did and didn’t.  Here’s two examples of no birth year showing:
![72850ADC-680E-4B5F-A762-585CC48503D2](https://user-images.githubusercontent.com/114665933/201755404-a5099ed0-2f90-4450-a0e5-a502b13215be.png)
![3AB92EEA-B9A3-4CE9-94EB-D581DFB93CA7](https://user-images.githubusercontent.com/114665933/201755418-30365d2f-1958-4796-825f-5e706284edcb.png)
What’s really weird is that in the change history, it looks like I went into the record after saving it and took off the birth year!  Which I swear, I did not!
![F0760B70-6FC6-48AA-AC49-F47A683336A9](https://user-images.githubusercontent.com/114665933/201755654-22acb009-01c8-488e-9832-a4bc2532fa40.png)

**Comment by PatientRowan** [comment]
Also (as in the time before) if I do an empty save, the birth year and place of birth magically re-appear.

**Comment by dfurber** [comment]
It is a strange behavior indeed. I think I fixed it. Please test and lemme know.

**Comment by dfurber** [comment]
Except that there is a new problem preventing deployment so don't get testing it just yet...

**Comment by dfurber** [comment]
And that new problem is at least subverted. So give it a try, and if it works, close this issue.

**Comment by PatientRowan** [comment]
I’m just sitting down to start testing.  Could you re-run the index to show the birth years there too?  Example: 
![EED13087-CC6E-4BC9-9B34-52FD5B3CFD37](https://user-images.githubusercontent.com/114665933/205649161-b017b4e8-9c28-4f8e-bf30-b4b10f3795fa.jpeg)

I’m aware that the Teeter family is a mess.  I’m kind of half-heartedly working on them.  The birth years displaying helps a lot.

**Comment by dfurber** [comment]
That's quite a Teeter patch. I re-ran the thing that calculates missing birth years.

**Comment by PatientRowan** [comment]
Teeter patch!  
Thank you for re-running the index.
I worked on ED 25:23 and all the person records looked right to me.
