### ISSUE TITLE
How to explain the person authority records and matching for revised project administrator's manual

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#138]
HI Dave, here's what I have to start (see below). I'm not sure how this will work with the new testing partners in terms of how a person id will be generated (automatically or manually) and when, as well as whether the matching algorithm will be in effect-maybe it doesn't need to be if when they start a second census as part of reviewing the census records they try to match each census record with one from the other census or if that's not possible, assign a person id. Please let me know.
Person Records-
Similar to the building records, the person record is an authority record that hosts census records from different census years for each person as well as information and photographs. Each person record will have a Person ID and once an installation has entered records for more than one census year an algorithm will start to “match” people from the different censuses. Those matches will have to be reviewed by volunteers to confirm the match.

**Comment by dfurber** [comment]
I invite @PatientRowan to comment as the authority on person records as a concept. From my end, the person record is the glue that ties together census records across years that match the same person. So your explanation looks fine.

**Comment by PatientRowan** [comment]
Let me get back to you tomorrow.  Heading into Sunday dinner with my mother.

**Comment by PatientRowan** [comment]
Thinking out loud here.  I have a specific question: For the first census year a testing partner transcribes, does the HF installation that you give the testing partner automatically generate person records for each census record individual?  Instantly, or in regular runs?  
We’re trying to picture it: 
    —the testing partner enters census records for a census year
    —the computer generates person records
     —then when the testing partner moves on to another census year, your matching algorithm kicks in and suggests matches
     —the testing partner either agrees to the match by clicking Match! or creates a new person record manually.  No more automation at that point.
     Is that the right understanding?  And is that what we want to do?

**Comment by PatientRowan** [comment]
If that is the procedure you and Eve are envisaging, then Eve’s wording is right on; appropriately a little basic but saying more would not help.
