### ISSUE TITLE
Parent address-on a different street-building on corner

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#139]
302 S Aurora was a new address in 1950, it is in the same building as 127 Prospect St which existed previously. I went to treat this like a duplex and tried to add 127 Prospect St as the parent address but the dropdown menu only has buildings in the building database in the 300 block of S Aurora. Darn that corner building, the parent address thing with the dropdown was great until this building went and messed it up.
302 S Aurora-https://tompkins.historyforge.net/buildings/8062
127 Prospect-https://tompkins.historyforge.net/buildings/7193

**Comment by dfurber** [comment]
Yeah, it could be improved. Instead of making it pick from buildings on the same street (like the building dropdown on census record), I'm changing it to include buildings within 0.05 miles. I can see this being a problem if you haven't located the building on the map yet.

**Comment by dfurber** [comment]
But that isn't likely to be an issue because you have to enter the address first and save the building anyway.
