### ISSUE TITLE
How to handle street name without a suffix-"The Byway" in Town of Ithaca

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#140]
Creating building records when the street name has no suffix is a little tricky. When I checked the box create building at this address it did house the census record and create a building record but the building record does not then appear in the dropdown menu for other members of the household. The workaround is to continue to check the box to create a building for each person. It does not create a new building but instead houses the census record to the same previously created building. So it works, but the problem is that it is not obvious that it works, some people might hesitate to house more records thinking it didn't work or that it would create multiple buildings at that address.

**Comment by dfurber** [comment]
The thing that makes it look up the buildings was waiting on a locality, house number, street name, and street suffix. I dropped the suffix requirement and it seems to work fine. Please close if you're happy with the result.

**Comment by dfurber** [comment]
I'll go ahead and close it. If you're not happy, please reopen.
