### ISSUE TITLE
Out-of-Order Pull-down Menu for Some Streets

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#141]
I haven’t got a bead on the circumstances in which this happens:
![70E9F1F2-4C45-4118-B69C-BDE6B1502EB1](https://user-images.githubusercontent.com/114665933/205494541-ddb7df08-7ad0-4d8a-ba2f-b07c83c565f4.png)

**Comment by dfurber** [comment]
The reason it is out of order is that it sorts it by address, and then translates the "address for year", so if that crosses a street renumbering, it goes out of order. I'm changing it to do the sorting after it's translated the addresses.

**Comment by dfurber** [comment]
Please close if you're happy with the outcome.

**Comment by dfurber** [comment]
I'll go ahead and close. If you're not happy, please reopen.

**Comment by PatientRowan** [comment]
Thank you.  I will test drive it tomorrow, but I’m sure it will be fine.
