### ISSUE TITLE
Unexpected, Random-ish Alphabetization

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#143]
I do a double-take when I see alphabetization like this:
![86E76012-9A69-4DBE-A4E9-DEAD8D50D3A9](https://user-images.githubusercontent.com/114665933/206865069-f631f617-b51c-43fe-a0b6-80eb298eb628.jpeg)
In catalogs I’ve used, all the plain Alberts would come before the Alberts with a middle initial.
And then this one is even more unexpected:
![09C60823-C5BF-4992-AFE9-D78E7A7876DA](https://user-images.githubusercontent.com/114665933/206865125-5991890e-6f64-4188-a3af-98bf838a5b4a.jpeg)
I’m filtering on “starts with,” which to me should result in strict alphabetization, but I’m not sure what order these results are in.  Birth year doesn’t seem to be a factor.
It’s especially confusing when you’re working on common names with a lot of hits like John Brown.

**Comment by dfurber** [comment]
If that's how the big boys do it, then that's how we shall do it.

**Comment by PatientRowan** [comment]
![image](https://user-images.githubusercontent.com/114665933/229384638-fde9f486-31c0-4be9-bc6c-b0dc721f7907.jpeg)
 Anthony Panizzi (91 Rules — 1841)

![image](https://user-images.githubusercontent.com/114665933/229384683-90ecf44a-8c92-45e3-9196-1b9a66e5879a.jpeg)
Charles Ammi Cutter (Rules — 1876)

**Comment by dfurber** [comment]
I take it these are the big boys?
