### ISSUE TITLE
Sometimes Comma before Title, Sometimes Not

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#144]
This is really small and trivial and I apologize about mentioning it.  On census record indexes:

![96A9E63A-B494-45AB-B323-17DE7D53901E](https://user-images.githubusercontent.com/114665933/206865276-72d269f0-6d02-41e2-bd93-8e7fc94b22f1.jpeg)

There’s a comma before the Revs. but not before Father.  Since my task was to review these records, I went into the Father Byrne’s to make sure that the transcriber had not put Father as a middle name, but no, the Father is in the Title area.

**Comment by dfurber** [comment]
Looks like the presence of the middle name is the determining factor.

**Comment by dfurber** [comment]
I cleaned that up, but still didn't like `Byrne, William, Father`, nor `Maloney, John S, Rev`. So I changed the formatting to `Byrne, Father William` and `Maloney, Rev John S`.

**Comment by PatientRowan** [comment]
Sort of fixed?  You’ve left it as before on the Person Record Index, which I think is much better for that situation where you really need to be comparing last name/first name:
![IMG_0371](https://user-images.githubusercontent.com/114665933/229505923-da2c8b53-7d1b-4ce1-8a04-dea3eb09b98b.png)
But on the person record, there’s a mix of styles:
![IMG_0372](https://user-images.githubusercontent.com/114665933/229506329-e9f0e198-20c3-4650-91e1-ac83d8b0c2c5.jpeg)

**Comment by dfurber** [comment]
I moved the title back to the end, and made the People behave the same way as census records.

**Comment by PatientRowan** [comment]
Thank you.  Trivia — the Library of Congress faced the same problem of how to present and index authorized name headings over a hundred years ago.  LC distributed card sets in their distinctive typeface with the name portion bolded, the titles and dates not bolded, sometimes in italics: 
![IMG_0387](https://user-images.githubusercontent.com/114665933/235448347-1c485bf4-b9cf-458c-808c-127bd00059e8.jpeg)
I’m still nostalgic about the old cards and the old rules.
