### ISSUE TITLE
Institution Name and Type—1950 Census—SAVE Issues and Display Issues

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#148]
The 1950 census form for has boxes for Institution Name and Institution Type on every individual’s record.  (The info actually comes from the top center-left of each census page, along with the lines that the name/type applies to.)
![DFE25D3A-96D3-43FC-A46A-231810647FE9](https://user-images.githubusercontent.com/114665933/207158692-23619392-f59c-4258-883c-e3ff2fc038a7.jpeg)

On a SAVE “in this family,” Institution Name and Type are currently not retained—you have to type the name and type into each individual all over again.

**Comment by PatientRowan** [comment]
Also, the institution name and type do not appear on the public view of the individual census record before you hit the Edit button.  This means that for reviewing, the reviewer can’t scan the page and see if it’s there.  I have to open each record, hit Edit, then look for the boxes to see if they’re filled in.  Transcribers often don’t know about institution name/type and don’t think to look up at the top of the sheet.
![AD4F797C-2535-415E-AC74-03C408793ACB](https://user-images.githubusercontent.com/114665933/207159557-06976950-2ac0-4289-bc33-4dd64a03ba39.jpeg)

**Comment by PatientRowan** [comment]
Also Institution Name and Institution Type do not appear anywhere on the Fields list:
![7E2B14C2-9C6B-4055-BA5A-EE3FA34751C9](https://user-images.githubusercontent.com/114665933/207160225-0860c406-be4c-465c-aba9-633e600db218.jpeg)

**Comment by dfurber** [comment]
Institution Name and Type are already showing on the field list. On another issue, I made "for this family" copy over the institution fields.  I had also added them to the census record detail page, however only when they were filled in. I've changed it to say "blank" when it's blank to keep with custom and eliminate confusion.

**Comment by PatientRowan** [comment]
Thank you very much.  It looks good and it will save me a lot of time although the County Farm is probably our biggest institution in 1950 and we’ve already done it.
