### ISSUE TITLE
Building Variants—Public v. Non-Public 

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#152]
Yesterday Eve and I changed the main building name of a friend’s house from 1036 W Seneca to the current 201 Floral Ave.
When I search by the old address in the public view, entering the variant name leads you to the current name:
![516878BF-D73A-4CC2-BF1D-04266CB665F1](https://user-images.githubusercontent.com/114665933/209813953-8fb04b0c-73c8-43bb-a688-1378501e05d3.jpeg)
But when I search by the old address in the non-public view, I don’t get any result:
![01C5D42D-D040-4D91-9561-B5B5938F8361](https://user-images.githubusercontent.com/114665933/209814060-fe169ab6-1598-49fb-8379-2edbaf5234d1.jpeg)

**Comment by PatientRowan** [comment]
Needless to say (but I’ll say it anyway) I am more concerned with this issue if it were to occur with name variants rather than building variants.

**Comment by dfurber** [comment]
Given that they'll be the same system, it's a worthy concern.

**Comment by EveSnyder** [comment]
Hi Dave, Sarah and I did an initial sweep of all of the person records, merging and unmerging records where we could. I know there will always be more to do on that front but I went ahead and made the person record database public so now anyone can see it from the Data drop-down menu. I noticed when I tried the name "Aagard" in the person search box on Tompkins HF homepage it gave me results from the 1940 and 1950 census but not the one from the 1930 census. Will that person search box continue to pull from the censuses or will it pull from the person record eventually?

**Comment by PatientRowan** [comment]
Using the same example as above, 201 Floral Ave/1036 W Seneca, I notice that Building Variants continue to display and be retrievable in the public home page, but not in non-public view.

**Comment by dfurber** [comment]
I found the problem. The code that helps it order the list by street address inadvertently limits the "street address" filter on the Buildings page to consider only primary address.

**Comment by PatientRowan** [comment]
Aha!  I tried out a Buildings search on “street address contains 1036 w” and got my 201 Floral Ave!  This is fantastic!
What does “not published yet” mean if it seems to work in the live database?
