### ISSUE TITLE
Puzzled—1920 Immaculate Conception Lacking from Building Record

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#154]
I went to one of the census records for the 1920 convent — “Unknown, Alpheus, Sister” — clicked through to the building record — and 1920 is missing:
![D7FAD1A6-6F29-466C-ABBA-8990AE5F7071](https://user-images.githubusercontent.com/114665933/210383019-93a6c014-86e1-4450-9c47-2c84d25a4afc.png)

**Comment by PatientRowan** [comment]
I still sometimes find building records not updating with new 1950 data?  Here’s one with no 1950 block, 108 Hillview Pl:
![1D8566EF-8C3F-49C7-93AD-0ECDA175BD17](https://user-images.githubusercontent.com/114665933/210383356-7984ec45-e9bf-4d94-93c0-779bd77fd814.png)
In this case, the record is not yet reviewed and made public—is that determinative?  Other records on this sheet (ED 25:Sheet 76) ARE visible.  I still think I’m missing other records, even ones I have reviewed.  But I may be wrong.

**Comment by dfurber** [comment]
I think it might only be showing census records that have been reviewed.

**Comment by dfurber** [comment]
So I'm making it show unreviewed ones as well if you're logged in. I imagine the nuns went unreviewed for 1920 because of what to do with "Unknown" as a last name.

**Comment by PatientRowan** [comment]
I see.  I was looking at the individual census records by clicking through, not retrieving them by a filter search on ED/Sheet/Side, which is the only way I can see the green “New” icon.  This is very helpful.
It’s not for me to say, but I’m pretty sure Eve @EveSnyder would not like unreviewed records to display to the public.  I will review and release the 9 nuns.  We seem to currently be using the word “Blank” instead of the word “Unknown” to satisfy the computer objecting to a blank field.  (I believe if the census said “Unknown,” we would transcribe it that way.  We want these rules to be simple).                                                  Eve, we want unrevised records suppressed from public view, right?

**Comment by dfurber** [comment]
Unreviewed records should never be displayed to the public. But they should be displayed to you. This particular path had lost some of its smarts in that regard, and wasn't showing unreviewed records to anyone.

**Comment by PatientRowan** [comment]
Oh, sorry—I forgot to look for the red Good to go! button.  Didn’t it used to be on the right hand side?  I gotta get sharper.

**Comment by PatientRowan** [comment]
That is absolutely ideal.  Thank you.  I’m closing this and will try to keep it in mind when I see something and my mother can’t see it because it is unreviewed.
