### ISSUE TITLE
Conditional Logic in Immigration/Naturalization Area, 1920 & 1930

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#155]
I’m sure you have heard about immigration law snafu where American-born women who married men who were aliens had to take the citizenship status of “Alien.”
Here’s what it looks like on the 1920 census that the Caroline team was working on recently. In this case, Effie Moore was born in New York, but her husband George is Canadian:
![FE18C55C-E5B5-4087-B766-45D451601A0D](https://user-images.githubusercontent.com/114665933/211194427-06b8bccc-d726-4c48-a095-3f40e93104e3.jpeg)
In the HistoryForge form, there’s conditional logic that only turns on “Naturalization” after you have checked the “This Person is Foreign Born” box YES.
![3B4117A2-0075-4D9D-99A6-BC526809E679](https://user-images.githubusercontent.com/114665933/211194518-68c344ca-0b07-4f43-ad6b-70e1c511625f.jpeg)
Could you take off the trigger function of checking the Foreign Born box?  I think it will be safe enough to leave it unprotected.  It’s not likely to be a field that transcribers would mess around with at random.  And it will be good going forward if we can more easily retrieve this interesting class of women.

**Comment by dfurber** [comment]
How do you like what I just did?

**Comment by PatientRowan** [comment]
I’m trying to edit [https://tompkins.historyforge.net/census/1920/17621/edit](url) and the Alien radio button remains grayed out.
Then again, if what you just did is anything like the longstanding Flag banner, it’s probably completely obvious and I’m just missing it.

**Comment by dfurber** [comment]
Sorry, the changes I made yesterday didn't get deployed to Ithaca and Walnut Hills. Now it should be good.

**Comment by PatientRowan** [comment]
Yes!  Let me check with Eve about 1930 (and maybe 1910?  I could look it up, but she’ll just know) and then I’ll close it.  Thanks!

**Comment by PatientRowan** [comment]
All good. 1920 only, Eve checked.
