### ISSUE TITLE
How to Flag and Harvest Person Record Problems 

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#156]
Eve and I have been talking over an E-Z way to flag a person record as what Eve calls a “problem child.”  We’d like a way for a HistoryForge worker (with authorization to work on person records) to flag a person record and write down all their notes about what the problems are.  The idea would be that somebody — either the original worker, if they find the time — or somebody else who’s good at research and problem resolution — could harvest the problems and work at resolving them.
My personal preference is to do this operation within HistoryForge, and not keep a separate external spreadsheet with a running list of the problems.  Eve would still like to be able to export the problem list to a spreadsheet, as filtering options in a spreadsheet can sometimes help.  We also want harvest to be simple for people with low levels of skill like me, and not too elaborate for you either.
Our best idea so far: Could you add to the list of fields you can Filter on, the “Additional Notes — Notes — Private field visible only to those who can edit this record”?  Currently only the public Description field is enabled.  The HistoryForge worker would start their private note out with the code “911,” then add all their research.
The list could then be harvested by filtering on 911.

**Comment by dfurber** [comment]
Is the "flag it" system not working?

**Comment by PatientRowan** [comment]
Neither of us saw the Flag button!  Is that terrible, or what?  It’s brilliant, and I should have known that you’d plan for it.  I have temporarily flagged young Andrew Aagard.
Is it possible to separate the flagged Person Records from the flagged census records, so that if Eve hands off the list to someone, they don’t have to pick through the whole list?
Also—not sure how Eve will see the issue of export to spreadsheet-given how neat the flag system is —

**Comment by dfurber** [comment]
Frantically working to make the flag system at least sort by type of flagged thing.

**Comment by PatientRowan** [comment]
Please don’t be frantic.  Sorting by flag type would be a nice-to-have for whenever, not critical.  You’ve already invented it and thought it through way ahead of us.  To be honest we’re not yet that close to trying person records with other HF volunteers, it was more a “How would we …?”

**Comment by dfurber** [comment]
It would in any case be cool if you guys would use the flag system and make suggestions. It's pretty simple / simplistic right now, assuming that you'll flag something then resolve it, not keep the flag around forever. It might need statuses, the ability to filter by status, and so on.

**Comment by dfurber** [comment]
But it is very much intended to be a running list of problems.

**Comment by PatientRowan** [comment]
Good.  Thank you.  We will figure out how to make it work.  My personal tolerance for long, lingering problem lists is low, but there will undoubtedly be calmer HF workers in the future who don’t panic when they see them.

**Comment by dfurber** [comment]
I don't think my improvements yesterday made it out. Please check now.

**Comment by PatientRowan** [comment]
I love it.  The Type column ought to be all we need, as long as we don’t let the list get too long.  I will close this issue after meeting with Eve this afternoon.

**Comment by PatientRowan** [comment]
All good.
