### ISSUE TITLE
Problem with The Forge?

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#158]
The Forge just has the map layers now and is missing the search boxes you added to the bottom. Also I can't map the results of a search-I get all the data.
In addition, every time I open The Forge on my computer, it opens to the results of some search I did earlier, even after I logged off and back on again. It also seems to be stuck on a particular historical map.

**Comment by dfurber** [comment]
I moved the search boxes into a different box - on the other side from the map layers button you should see a search button. But I'll try moving it to make it more obvious to seasoned hands.

**Comment by dfurber** [comment]
One of the improvements I made was to make it remember which filters and map layers you had going. But this was not obvious. I just made it check if there is an active search or layers checked, and if so, to offer a reset button.

**Comment by EveSnyder** [comment]
I see that and I think its cool but when I hit reset it resets initially but then when I go back to The Forge later it reverts to the results of the last search even though I'd already reset it.
