### ISSUE TITLE
1910 census language spoken help text

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#166]
I just revised the help text for language spoken for the 1910 census on the census label doc, could you please change the help text accordingly. 
The new text reads-Enter what you see on the census. If the enumerator wrote un (see below) or don’t know enter Unknown. Note: This field has a controlled vocabulary. If, as you enter the term from the census, the term does not appear from the list of controlled vocabulary, enter an X in the field and enter “Language spoken is ____” in the notes field.

**Comment by PatientRowan** [comment]
I tested this field out by trying to enter the language “Klingon,” which is authorized in the controlled vocabulary of library world.

**Comment by dfurber** [comment]
Pretty sure no one in 1910 spoke Klingon. :)
