### ISSUE TITLE
1910 help text civil war

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#168]
Just revised in census label doc, please update to include that language (below) and keep the image.
Select the option that corresponds to the answer on the census. *Note: Columns 30-32 will sometime include a series of annotations rather than responses to the questions themselves (see image below). These annotations were the key-punch symbols used for post-enumeration processing of the census. If this is the case, do not check the boxes and do not enter this information into the Notes field.

**Comment by EveSnyder** [comment]
Also if possible could you make the image a little smaller.

**Comment by dfurber** [comment]
Give me a smaller image and I can pop it in.
