### ISSUE TITLE
Permissions for Person Records — Merge & Delete Lacking

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#176]
Eve and I were showing Caroline Arms person records today.  She was given permission to edit the person records.  We found that she can Create a New Person Record and Match, but she cannot Merge.  No button comes up for her to initiate the Merge action.  This must be a permissions thing, right?

**Comment by PatientRowan** [comment]
Caroline Arms also does not have a Delete button.

**Comment by dfurber** [comment]
Indeed it is a permissions thing. I gave the "person record editor" the same permissions re: person records as a "builder" has re: buildings, and an "editor" has re: census records. I suppose we could allow builders and PRE's to merge. I hesitate to allow delete, but we can give it a go.

**Comment by dfurber** [comment]
I continue to hesitate on letting builders tear down buildings when merge is available. But PRE's can now delete and merge person records.

**Comment by PatientRowan** [comment]
Eve,
    Great news for Caroline Arms!  Is she still in England?  Would you let her know about this, or would you like me to write her?
     Could we set up a time for Matt Watros and Helen McClallen to come in and get started?
—Sarah

On Mar 18, 2023, at 10:40 PM, David Furber ***@***.***> wrote:

﻿

Closed #176<https://github.com/historyforge/historyforge/issues/176> as completed.

**Comment by PatientRowan** [comment]
I am glad that I don’t have anything to do with building records.
