### ISSUE TITLE
creating building record by building name (when there is no street number)

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#181]
I recently did this and it worked but I wanted to make sure this is what is supposed to happen-
We had people in the 1950 census who lived at the Cornell Floriculture Testing Garden building, the building burned down in 1952 and did not have a street number at the time that we can find. So I added the building name in the house number field followed by the street, etc. Then I clicked add building at this address. I repeated this process for the other family members including checking the add building box since no building at that address appeared. Is this the best way to handle that situation? If so, I will add it to the manual.

**Comment by dfurber** [comment]
I guess that works.
