### ISSUE TITLE
Important for Walnut Hills—Suppl. Q’s POB Father & Mother—Prefills Ohio

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#183]
Ouch!  I could swear you’d fixed this, but it’s back.  On the 1940 census, every individual census record has a supplementary section, and every supplementary section is PREFILLED with a Place of Birth - Father and Place of Birth - Mother.  But there’s 40 lines on each sheet and maximum only 2 of them get supplementary questions, so all those prefills are wrong 38 out of 40 times.  Let alone if the person happens to have been born out of state, which we don’t know because they didn’t answer the suppl. question.
    For the Walnut Hills installation, POB Father and Mother is prefilling with “Ohio.”  Please remove.  The Walnut Hills folks are currently blanking Ohio out by hand, but that is not a long term plan.
    Mysteriously, the program has also gone back to prefilling with “New York” on Tompkins records.  Thank goodness we are not actively adding 1940 records, but we do also need it fixed here.
    I don’t have a login for Walnut Hills.  This is what it looks like on New York:
![E4EAEA64-F0ED-4427-B32E-9F539792A7AA](https://user-images.githubusercontent.com/114665933/217358257-835558e0-1c2d-4ec8-9474-9e5838171f6f.jpeg)

**Comment by dfurber** [comment]
Ouch! Fix will be up soon.

**Comment by dfurber** [comment]
Fixed and just verified.
