### ISSUE TITLE
Priority—Person Record Creation for Walnut Hills

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#189]
@Eve hears from Walnut Hills that they are interested in creating and editing Person Records from the get-go.

They would like to have the Create New Person Record available for them to use by hand, to record information about problems with a name and to hold biographical information.

JoAnn also has a nifty system going where she interacts with a downloaded Excel spreadsheet of her census sheet, notes her corrections on the spreadsheet, then goes into the HistoryForge records she needs to correct ONLY ONCE to make all her corrections.  The necessity to go into absolutely every HF record one-by-one and hit that Create button (assume no true matches in the first census year in Walnut Hills)—that is kinda inefficient, fine for Luddites like me but grinding Walnut Hills’ gears.

For Walnut Hill’s first census year, could you run an automatic Person Record creation on an regular basis, like maybe weekly, as you did for Ithaca censuses?  If Walnut Hills creates person records by hand for every individual they have info about, then the remainder should be safe to automate, right?

Alternately, if it would be easier which I doubt, maybe you could implement the extra button I was suggesting in Issue #151?  That way Walnut Hills could generate the needed person records themselves.

**Comment by dfurber** [comment]
I just added that button from issue #151 so let's see how that works.

**Comment by PatientRowan** [comment]
I can’t wait to test the button from #151.  Tomorrow!  Thank you!
      Can I just say my opinion here, @EveSnyder, Dave, see what you say: I understand that there may be a small number of cases where a new installation will want to create a person record by hand, in order to add annotations to the Description field while they’re fresh in their mind.  But as a general matter, I think it’s far more efficient to let the computer create the bulk of the person records programmatically.  New installations will have plenty of other issues they need to deal with, without generating person records by hitting buttons—to almost zero benefit, as there will be close to zero true matches in their first census year.
     If you had to imagine it, Dave, how often would you care to run an automatic person record creation job?  “Never” is a fine answer, I just want to have asked.  But if you were signing up to do something for Walnut Hills, we’d have to tell them the schedule.
