### ISSUE TITLE
Suggested Changes to Developer Setup Pages

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#193]
Posted on behalf of Silver Spring user (see e-mail):

re: https://github.com/historyforge/historyforge/wiki/Developer-Setup

In the "Prepare the Database" section:

CHANGE line:
cp config/database.yml.example config/database.yml

TO to:
cp config/database.example.yml config/database.yml

---------

CHANGE line:
rails schema:load db:seed

TO:
rails db:schema:load db:seed

-------------
Suggested code change in import.rake

 ~/historyforge/lib/tasks/import.rake, line 11,

CHANGE: 
unless file.exists?

TO:
unless file.exist?

the method FILE.exists was deprecated in Ruby 2.2, and in version of Ruby I used (version 3.2.1), FILE.exists now results in an error
see: https://ruby-doc.org/core-2.2.0/File.html#exist-3F-method ]

**Comment by dfurber** [comment]
I did the 3 things :)
