### ISSUE TITLE
Income for 1950 census -line item not working correctly

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#197]
For example income is sorted as all instances of - 10, 100, 1000 then 102, etc.

**Comment by dfurber** [comment]
That's because it's stored as a string, which is the price of being able to say `Un` and `$10,000+` as well as store a "number".

**Comment by dfurber** [comment]
Fix on the way that works like `family_id` which used to be a number but became a string to accommodate `A` and `B`.
