### ISSUE TITLE
GoogleMap api key

### ISSUE THREAD

**Issue by wmartin2** [historyforge/historyforge#205]
Need to set GoogleMaps api key in order to render maps.  Is this done somehow in .env file?

**Comment by wmartin2** [comment]
Cannot import data without the GoogleMaps api key.  I have a development key, but do not know where to add it.
 
TRANSACTION (0.2ms)  BEGIN
  ↳ app/models/building.rb:337:in `check_locality'
  Locality Count (0.3ms)  SELECT COUNT(*) FROM "localities"
  ↳ app/models/building.rb:337:in `check_locality'
Google API error: request denied (You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account).
  TRANSACTION (0.4ms)  ROLLBACK
  ↳ lib/tasks/import.rake:57:in `block (3 levels) in <main>'

**Comment by wmartin2** [comment]
I have set google_api_key to my [Maps API Key] in the settings table for databases historyforge and history forge_test.  Tried loading 1880 data, but still get google api errors and no data gets loaded into public.census_1880_records.

**Comment by dfurber** [comment]
Please check Admin -> Settings -> API Keys. It's looking for the `geocoding_key` in the settings table, which is usually the same but isn't always.

**Comment by wmartin2** [comment]
I needed to enable the geocoding api in my GoogleCredentials.  I no longer get Google authentication api errors.  Nothing gets imported as all transactions get rolled back.  I suggest adding a list of essential environment variables to the development wiki.   This issue seems to be resolved.
