### ISSUE TITLE
Log In -indicate for volunteers

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#211]
Could you add (for volunteers) after Log In on the Navbar to let people know that is only for volunteers.
see for example- https://informationwanted.org/get-involved
but using (for volunteers) instead of limiting it to transcription.

**Comment by dfurber** [comment]
That's the case now, but not when we get to allowing the public to sign up and upload photographs.

**Comment by dfurber** [comment]
I added "Volunteer" to the word "Log In" on the login page, and in the menu moved it to the end, right after the word "Volunteers". Please reopen with further guidance as needed.
