### ISSUE TITLE
Field displays on census database out of order for those not logged in

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#212]
If you're logged in the default fields in the census databases display in the order they appear on the census.
If you're not logged in they display out of order. Could you make them all display as they would on the census even if you're not logged in?

**Comment by dfurber** [comment]
Please be more descriptive. Give me a URL and perhaps some screen shots marked up so that I understand.

What I understand is "click on Data -> 1910 US Census while logged in. Then open an incognito window with the same URL. The fields on the grid will be in different order". However when I do that, I don't see any difference. Thus I need more guidance.

**Comment by dfurber** [comment]
@EveSnyder and @PatientRowan ^^

**Comment by PatientRowan** [comment]
I’m never not logged in, and I don’t know.  I’ll ask @EveSnyder this afternoon.

**Comment by EveSnyder** [comment]
I logged out to do some screenshots for a document showing people how to search on HF. When I first went to the 1910 census database the address displays all the way over to the right. The year doesn't matter it does it for other years as well.
<img width="583" alt="Untitled 2" src="https://user-images.githubusercontent.com/57808782/235681955-5e5f5c73-70eb-4986-b77b-f3c9cddcb0d7.png">
Can you see the image?

**Comment by EveSnyder** [comment]
Okay that was not the image I thought I was attaching but the good news is now I know that's how to attach an image. I'll try again.
<img width="1355" alt="Untitled2" src="https://user-images.githubusercontent.com/57808782/235682819-99ab87b8-4621-4808-8bee-6d0911fca7c9.png">

**Comment by PatientRowan** [comment]
﻿I can see the image.  And I can see it is out of order.  That ought to make it clear to Dave.
Should I post your screenshot to GitHub?  I know you usually don’t but I can’t remember if you had set up a method for yourself.

On May 2, 2023, at 9:37 AM, EveSnyder ***@***.***> wrote:

﻿

Okay that was not the image I thought I was attaching but the good news is now I know that's how to attach an image. I'll try again.
[Untitled2]<https://user-images.githubusercontent.com/57808782/235682819-99ab87b8-4621-4808-8bee-6d0911fca7c9.png>

**Comment by dfurber** [comment]
It's more that once you select fields, it goes into the order of the census form. Before then it goes in a different order that is defined separately as "default fields".

**Comment by dfurber** [comment]
I finally had the brilliant idea to put the default fields in the same order as they would show when logged in (most of the time anyway...).

**Comment by PatientRowan** [comment]
Thank you, Dave.
