### ISSUE TITLE
Help Text, 1940, Mother Tongue

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#217]
@EveSnyder and I discovered a problem with the 1940 help text for Mother Tongue in the supplemental questions.  The first sentence currently reads “Generally, for foreign born only.”  It was actually consistently used for ALL persons in 1940.
Could you please delete the first sentence of the help text?
Eve has already updated the language in the census labels Google sheet.

**Comment by dfurber** [comment]
This is live on Tompkins HF.

**Comment by PatientRowan** [comment]
Nice.  Thank you.
