### ISSUE TITLE
Enable Filtering on Race in Person Record Index

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#222]
Similar to Issue #221, @EveSnyder and would like to be able to filter on race in the person record index.  Beyond the authority control issues that race can help us with, we imagine any number of user groups might like to be able to retrieve a complete set of all persons of a particular race across census years.

There’s a wrinkle: without changing anything on the census records, Eve would like the person records to collapse the three categories for Blacks — B-Black, M-Mixed/Mulatto, and Neg-Black — into one, B-Black.  Users would still be able to find the Mixed/Mulatto category by searching the census year.  But we feel that the use case for retrieving all the Blacks in HistoryForge, whatever the census was calling them in that year, is strong.

Retrieving the Black set is the main goal of this ticket.  We did experiment on finding “Other” in the 1940 census by searching on Race “is not one of” and checking all the available buttons, and felt that the results were good enough.  I don’t know if you want to add Other as a button to the Person Record.

**Comment by dfurber** [comment]
This is live on Tompkins HF.

**Comment by PatientRowan** [comment]
![IMG_0438](https://github.com/historyforge/historyforge/assets/114665933/60ce02de-c9fa-44c2-aeec-a333ea1050fb)
 
I’m worried about the two “Blacks.”  We want the general public to be able to use this feature, and they are not going to understand that one of the “Blacks” is a disguised “Negro.” I’m OK with not collapsing all 3 into one, since your checkboxes are so elegant, but maybe could we collapse the two Blacks into one box and keep the check box for Mixed/Mulatto?  Perhaps you could keep all 3 by calling one of Blacks “Black (Negro)” but that is weird, isn’t it?  Of course the whole point is that the census, like all artifacts of American life, is weird about race.
If you keep all 3, is it possible not to separate the first two from the third with an interjected “Mexican”?

**Comment by PatientRowan** [comment]
Something seems to be going wrong with Mulattos turning up on the results of list when I try “Race is not one of” and check all the check boxes:
![IMG_0440](https://github.com/historyforge/historyforge/assets/114665933/6c566cbd-aa55-404f-8dec-52be6c1b4627)
I have not yet checked if these Mulattos are also being retrieved with search on Mulatto.

**Comment by PatientRowan** [comment]
Ah.  The Mulattos checkbox retrieves persons with “M” in their Race column, but nobody with “Mu” in their Race column.  I can’t remember what workflow we have had that would have caused this.

**Comment by PatientRowan** [comment]
Chinese appears only on the list of “Not One Of” with all the boxes checked.  A filter on just the checkbox Chinese retrieves 0.

**Comment by PatientRowan** [comment]
Results lists are not in alphabetical order.  See screen shot above for an example, but it seems to be general for searches on Race.  Search results on Place of Birth come back in alphabetical order.

**Comment by dfurber** [comment]
Reopened because it looks like a can of worms. Maybe "mulatto" was "Mu" in one census and "M" in others.

**Comment by PatientRowan** [comment]
I agree that the M/Mu problem is troubling, both here and on the 18XX censuses; Eve will be away for the nest couple of days and I do not want to try to get a hold on it until she’s back.
Note that the problems are not confined to M/Mu, there are also problems with Chinese as a checkbox versus Other.

**Comment by dfurber** [comment]
I think these issues are either fixed with the recent work, or accounted for in those issues.
