### ISSUE TITLE
Display Building Address Variants in Chronological Order on Census Record

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#226]
Posting on behalf of @EveSnyder who recently CONQUERED the insanity of Spencer Street’s address schemes over time:

The building record displays a building’s addresses in nice reverse chronological order:
![IMG_0423](https://github.com/historyforge/historyforge/assets/114665933/995bb73c-82a6-471b-af4d-ef6eedebb81e)

But the individual census record displays the same information in a chronological jumble:
![IMG_0422](https://github.com/historyforge/historyforge/assets/114665933/7efc6c07-d737-400d-96bc-ecec36ee4500)

**Comment by dfurber** [comment]
Interesting problem! Hopefully solved now

**Comment by PatientRowan** [comment]
I regret that I am taking this problem from “interesting” to “cursed” but I must report that the Spencer street public record is out of order this morning:
![IMG_0436](https://github.com/historyforge/historyforge/assets/114665933/ae77f844-5836-442f-b065-5d961c54d473)

**Comment by dfurber** [comment]
Should be good now, reopen if not please.
