### ISSUE TITLE
Save “On the Same Street” Blanks Out the Building Pull-Down on the Next Record’s Prefills

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#227]
The building pull-down for housing is mostly working well.  There’s one problem that experienced transcribers just deal with but which we have to translate for new transcribers—“Here’s how it ought to work in theory, and here’s the work-around”—so I’m opening an ticket on it at @EveSnyder ‘s request.

It’s not a fluke, it happens reliably.  To show screenshots, I input a census record at 402 N Geneva St, saved On the same street, and then started to input a record at 326 N Geneva St.  I have since deleted my work, as it was just for demonstration.

Here’s the record I started with:
![IMG_0425](https://github.com/historyforge/historyforge/assets/114665933/414078a1-8364-4370-9587-6ef90a4cd573)

And I saved it On the Same Street:
![IMG_0426](https://github.com/historyforge/historyforge/assets/114665933/2da64070-257e-4726-99e9-238a187be972)

Started the next record and hit the problem with the building drop-down menu being blank:
![IMG_0424](https://github.com/historyforge/historyforge/assets/114665933/e8ac8e48-e5fe-489f-b175-e59e98f42b8e)

**Comment by PatientRowan** [comment]
I should add that the pull-down menu is not always blank.  Sometimes it shows a menu of addresses on a completely unrelated block.  I have not been able to figure out where those addresses come from.  I have never transcribed any Newfield addresses, but I remember when I was reviewing Newfield records, I’d have Newfield addresses appearing in menus of my Ithaca work.  It was a period when Matt was working very intensively in Newfield and maybe the system was looking for the addresses most recently used?

**Comment by dfurber** [comment]
This is live on Tompkins HF.

**Comment by PatientRowan** [comment]
I will test this as soon as I can, but not today, due to circumstances.

**Comment by PatientRowan** [comment]
We stress-tested this today in the transcription session, and it’s great, thank you.  I would close the issue except I wasn’t sure if you wanted to do more to it, with the “Fixed—Not Published Yet” label but “live on Tompkins HF.”

**Comment by dfurber** [comment]
I just didn't want to close the issue until all the HF instances have it.
