### ISSUE TITLE
Building record-Attach Files (tab in the Description section)-doesn't work

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#231]
It will allow you to upload a file or at least go through the motion of uploading a file. I added a 1-page pdf to try it out. I got this far
<img width="1029" alt="Untitled1" src="https://github.com/historyforge/historyforge/assets/57808782/123a73ef-3780-4b96-adbb-80bca696db28">
But when I saved the record it disappeared and nothing happened.
For the documentation for new testing partners-what kind of files should we be able to attach and what is the max size?

**Comment by dfurber** [comment]
That shouldn't be there. I'll remove it.

**Comment by dfurber** [comment]
Overall the whole editor looks broken :( so much for "It's part of Rails now, that'll make it easy to maintain."
