### ISSUE TITLE
Quality of the Person Matching Algorithm

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#238]
When we first started using the matching algorithm for person records, I was delighted with it.  It was so smart!  I don’t think I have become more jaded with heavy use; it seems to me that it isn’t as good since the spring.
Here is an example: Silas and Sarah Wood, who first appeared in the 1940 census, are enumerated in the 1950 census as Silas and Sarah Woods.  The program did not suggest a match between Wood and Woods, I found it by hand because I’ve become very suspicious of the program.  I swear the old program would have picked that up.  Not that I know for sure, of course.

![IMG_0449](https://github.com/historyforge/historyforge/assets/114665933/75dc2a58-95a0-44ae-bea0-c136eb1cd1cf)

I don’t know if there is anything you can do about this, and we can certainly cope with the program as it stands, but I wanted to put it on the record.

**Comment by dfurber** [comment]
So I did two things.

First, I changed it from using "double metaphone" to "trigram with word similarity" to match the names. That will make "Wood" and "Woods" match. That caused Silas Wood to show up, among a dozen other Wood and Woods.

Second, I saw that the method it uses to match names is called `last_name_search` and that I was just passing in the last name, even though the in-aptly named method was searching against first and last name. I changed it to pass in the first and last names. Low and behold, Silas Wood was the only match.

**Comment by PatientRowan** [comment]
Thank you.  I’ll keep an eye on how it’s doing, without over-reacting to its minor mysteries.

**Comment by dfurber** [comment]
You'll reopen if there's new issues.

**Comment by PatientRowan** [comment]
Complaint about quality of matching, FYI, but not opening the issue at this point, just venting:

See person ID 33371, Thomas Carrican.  He was established in 1930 as Tom Carrican.  When I entered him today for 1950 as Thomas Carrican, the matching algorithm did not suggest Tom Carrican.  That’s one name the algorithm ought to know about.  (No issue going on with date of birth).

**Comment by PatientRowan** [comment]
Similarly, Sam Carrican born 1926, ID 33381, was little Sammie Carrican in the 1930 census.  When I entered him as Sam Carrican Jr in the 1950 census, a match between Sam and Sammie was not offered to me.  I consider this underpowered.

**Comment by PatientRowan** [comment]
No match offered: Person ID 35624:
 1930 = Bond, W Bradford
1950 = Bond, Bradford
 (No DOB issue).

**Comment by PatientRowan** [comment]
No match offered: Person ID 31941
1930 = Robinson, Ray W
1950 = Robinson, Raymond
(1940 Raymond had made it onto the Ray record; somehow this version of the algorithm doesn’t recognize Ray/Raymond match)

**Comment by PatientRowan** [comment]
See the results offered for Orr, William.
Every so often the algorithm offers a list of everyone with the same first name that’s in the right age range.  In this case, every William.  No match.  But what causes it to generate this long, long list?

**Comment by PatientRowan** [comment]
Starting with:
1940: Miller, Katharine (age 3)
No match offered with:
1950: Miller, Kathryn G (age 12)

This is an example of the algorithm not having a large enough dictionary of similar names and nicknames.

**Comment by PatientRowan** [comment]
In the Complete Mystery department:
1930-1940: Spencer, Ruth R (age 31, 41)
No match with the exact same name
1950: Spencer, Ruth R (age 51)

**Comment by PatientRowan** [comment]
And that is not the first complete mystery recently, either, I just don’t feel like documenting it all the time, or hope it was something I was overlooking

**Comment by PatientRowan** [comment]
1930: Robinson, Philip J — age 31
1940: Robinson, Philip — age 41

Match NOT offered with:

1950: Robinson, Phillip J — age 50

Wait—it’s defeated by Philip/Phillip??

**Comment by PatientRowan** [comment]
Same family as the Philip Robinson family above:

1940: Robinson, Phyliss — age 1

Match NOT offered with:

1950: Robinson, Phyllis J — age 11

**Comment by PatientRowan** [comment]
1950 census: Brown, Ray — age 66 

No match offered with 1940 census:

Brown, Roy — age 56

Example of the algorithm needing to be bolstered with a thesaurus of similar names/misspellings/nicknames

**Comment by PatientRowan** [comment]
Header: J Howard Best (I changed it to John Howard Best)
1920 census: Best, John H  — age 44
1930 census: Best, J Howard — age 54
1940 census: Best, J Howard — age 64
1950 census: Best, John H — age 74

No match offered to 1910 census
Best, Howard — age 35

Program should be first/middle name agnostic

**Comment by PatientRowan** [comment]
The quality of the matching algorithm is definitely worse this morning.  No ranking going on in the matches offered?so that the exact match, which should be the top match and perhaps sometimes the only match, is instead buried at random in the long right-hand column

**Comment by dfurber** [comment]
I’ll take a look.

**Comment by PatientRowan** [comment]
In my opinion, we're good now.  I might make small additions to the cognates list, but I am satisfied that expected matches happen.
