### ISSUE TITLE
Important-can't add locality to the census form on Pittsburgh HF-can't add/save census records

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#245]
We had a training with Pittsburgh HF yesterday and when we went to select the locality nothing happened. We entered the rest of the census record but could not save it without the locality. Could you make their locality autofill on the census like on Walnut Hills? Could that be a standard feature for any installation with a single locality?

**Comment by dfurber** [comment]
There is an outstanding issue that I haven't figured out, wherein after you add the locality, it sometimes doesn't show up in the list of localities on the census form until I restart the server. Clearly it's getting cached somewhere but I'm not sure where.

**Comment by dfurber** [comment]
I think I figured it out on the Walnut Hills rendition of this issue. Closing as a duplicate.
