### ISSUE TITLE
Filter on Street Address Broken for Census Years

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#246]
I am trying to figure out what happened to the Drake family in 1930 when they were not living at 701 N. Aurora St.  I want to filter on 701 N Aurora St in the 1930 census (did anybody live there?).  No search that I enter retrieves less than 22,321 records—starts with, contains, contains all of.  Won’t bother showing you all my permutations, but here’s one:
![IMG_0461](https://github.com/historyforge/historyforge/assets/114665933/c7942ac8-f17a-4e5c-926e-0267ad13cbf4)
    I have noticed this problem in the 1950 census as well, when I’m working on the catch-up sheets that don’t have a Serial No. but do have an address, and I’m trying to determine if the persons at the address are their own household or part of an already-enumerated household.
     I do not experience this problem with searching on street address in the Buildings file.

**Comment by dfurber** [comment]
I fixed this earlier today under a different issue. Re-open if I am mistaken.

**Comment by dfurber** [comment]
The problem is for street address, you can't just enter "Aurora". You need to enter it like "405 N Aurora St". Annoying I know, and thinking about a solution.

**Comment by PatientRowan** [comment]
So I tried entering “contains 945 Cliff St” which is a complete address as used on 1930, Ward 1, ED 17, Sheet 1A.  And I got the same results of the entire 1930 census—22,321 records.

**Comment by PatientRowan** [comment]
Great!  Pittsburgh was just asking @EveSnyder  about this feature.  Do you have to publish the fix in each installation separately, or does it go out to everybody automatically?
