### ISSUE TITLE
building merge problem for Walnut Hills

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#247]
Message from JoAnn:
I think that the merge function is backwards. I’m attaching 3 screenshots. The correct address is 1410 Myrtle. It got entered as 2410 Myrtle. I corrected one census record to 1410 Myrtle, adding a building at that address. Then I went into Buildings and tried to merge 2410 into 1410. I’m attaching 3 screenshots:
 
Setting up merge: I’m in the 1410 building record and have clicked the Merge button. I select 2410 as the building I want merged INTO 1410.
![SettingUpMerge](https://github.com/historyforge/historyforge/assets/57808782/da9c880b-c90f-49ce-8f6f-61200b364a57)
Before merge: Words indicate that 2410 will disappear.
![BeforeMerge-2410 should disappear](https://github.com/historyforge/historyforge/assets/57808782/305520b7-bb36-40e1-abe2-967526c0f260)
After merge: 2410 remains and 1410 has disappeared. Census record that I changed to 1410 has been changed back to 2410.
![After Merge-2410 Remains](https://github.com/historyforge/historyforge/assets/57808782/f2f95722-aa82-43bf-a8d3-85fb2233bb80)

**Comment by dfurber** [comment]
It wouldn't be backwards for one instance of HF since it all uses the same code. Do you experience this problem for Tompkins?

FWIW I went in and changed the address on 2410 to 1410 and it looks fine.

**Comment by dfurber** [comment]
I also don't know why she didn't just change the address on the 2410 Myrtle to 1410, rather than create a duplicate building through a census record and then trying to merge the dead building into this one.

**Comment by dfurber** [comment]
Because the merge wasn't ever going to make the 2410 address go away, but tack it onto the address history of 1410.

**Comment by dfurber** [comment]
One undesired behavior that I am removing is that it tacks the source building name onto the target building name, but it never gets displayed. I think that might have confused Walnut Hills. The name field was full of gunk but it only displayed the first line.
