### ISSUE TITLE
1850, 1860, 1870 censuses won't save

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#252]

**Comment by PatientRowan** [comment]
FYI it is the new 1850-1860-1870 forms for Tompkins County that can’t save.

@EveSnyder It sounds like the problem that Pittsburgh was having with being unable to save their 1920 records has been fixed?

**Comment by PatientRowan** [comment]
Today, the 1860 saves!
I’m only leaving this issue open because we have not tested the 1850 and 1870 censuses.

**Comment by EveSnyder** [comment]
The 1850, 1869, and 1870 censuses have all been tested and they all save.
