### ISSUE TITLE
1860 Institution Name/Type Placement

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#254]
I was trying to ignore this on our test drive on 1860 in order not to bother you.  My apologies.

@EveSnyder and I thought that the census form ought to follow the layout that the census instructions give about writing the institution perpendicularly between dwelling and family numbers.

But in practice, it doesn’t seem to work for inputting to have Dwelling and Family numbers separated by Institution Name and Type.  It’s too easy not the hit the right box, and institution name/type hardly ever happen.  Could you put Dwelling and Family numbers together, followed by Institution Name and Type?

![IMG_0479](https://github.com/historyforge/historyforge/assets/114665933/e78b50d3-7ecc-4561-9dec-9ffe767daf22)

**Comment by EveSnyder** [comment]
This looks fixed to me.
