### ISSUE TITLE
1850/1860 census-Institution name/type does not display in list of fields/filters on database view or census record

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#257]

**Comment by PatientRowan** [comment]
Reminder to Sarah to get a new screenshot for the Reviewer’s Guidelines when this has been fixed.

**Comment by EveSnyder** [comment]
This is not an issue for the 1870 census, I checked.

**Comment by PatientRowan** [comment]
Not yet displaying in 1850 and 1860–not published yet—so I cannot check it.
