### ISSUE TITLE
Spurious 1950 Merge Messages "You Might Reconsider"

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#258]
I keep seeing these messages in red along the bottom when I merge a person who has a 1950 appearance.  As far as I can tell, it only occurs with 1950 census records.  I don't know if it's every time I merge a 1950 person, or just sometimes.

![Screen Shot 2023-08-17 at 7 51 14 AM](https://github.com/historyforge/historyforge/assets/114665933/aca23044-b27d-4f16-912e-deb0c5d5afad)

It's a variation on the "You Can't Do This Merge" message saying that you're asking for a merge that would result in the same person having two appearances in the same census year.  But so far in my experience, this message is never true: the person has only a single 1950 appearance, there is not a same-year census record in 1950.

I say Yes Please anyway and the merge goes through, so it's not a big problem, but confusing!

**Comment by dfurber** [comment]
What an amazing catch! It's a copy and paste error, easy fix.
