### ISSUE TITLE
Find a person — Find your house off the home page

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#264]
We’ve talked before about the two searches off the home page, Find a person and Find your house.  They seem to be very dispirited at the present time.  I can’t find my go-to guy, Ebenezer Miller, no matter what combo I type into Find a person.  And @EveSnyder told me yesterday that she had been unable to find 401 E State St (Gateway Center) using Find your house, although I’m finding it this morning.

The reason I’m driven to write today is that last night I accompanied Eve on the Discover Cayuga Lake cruise where Eve gave a lecture on boatbuilding.  At the end of the talk we handed out a page on How to History Forge.  Eve had written it with the premise that the two searches on the home page were likely to fail, and offered other search strategies to help new or casual users get some results.

Talking to the two nice ladies who seemed most interested in Eve’s pitch, I wished I had not needed to show them the Data drop-down menu right off the bat in order to get anywhere.  If I hadn’t been showing them HistoryForge in person, and if they didn’t have Eve’s cheat sheet, they might have tried a search on the home page, failed, and wandered away.

Do I sound like a proselytizer complaining about the user-unfriendly font that their sacred book is printed in?

**Comment by dfurber** [comment]
No, it sounds like the feature is broken. I also think that person records have matured enough that we can make "Find a person" find people rather than census records. I hooked it up to the search method I set up for person matching, and it works fabulously.

**Comment by PatientRowan** [comment]
It’s lovely.  You’ve designed such an elegant tool.
Please consider comments relating to #152 (Building Variants) and #125 (Name Variants).
