### ISSUE TITLE
Add Map Overlays from External Sources

### ISSUE THREAD

**Issue by mradamcox** [historyforge/historyforge#265]
Hello! I am working with the [Southeast Louisiana HistoryForge](https://sela.historyforge.net) where hope to incorporate map layers from OldInsuranceMaps.net, which can provide XYZ or WMS endpoints for mosaicked Sanborn maps.

It looks to me like HistoryForge is built around some [custom WMS configurations](https://github.com/historyforge/historyforge/blob/master/app/javascript/forge/wms.ts#L72) that are tailored specifically to MapWarper. Is there any guidance out their for how to get an non-MapWarper WMS layer into HistoryForge?

I have tried to augment the OldInsuranceMaps.net WMS service to mimic these configurations, but without any significant progress so far.

**Comment by dfurber** [comment]
Done

**Comment by mradamcox** [comment]
Splendid, the new layers param will allow us to use any WMS from OldInsuranceMaps.net. Thank you!
