### ISSUE TITLE
Upload pre-georeferenced maps to HF MapWarper

### ISSUE THREAD

**Issue by mradamcox** [historyforge/historyforge#266]
Related to #265 where we are looking to incorporate external web services, we are also open to uploading GeoTiffs directly to MapWarper, so we can serve them into HistoryForge as usual.

MapWarper is meant for the upload of non-spatial images so the georeferencing can happen online within that system, but, if possible, we would love to be able to use maps that we have already georeferenced elsewhere. Is this possible?

**Comment by dfurber** [comment]
Closing because we would rather not upload maps to MapWarper that you can serve with your own map server.
