### ISSUE TITLE
1850-1870 help text screenshot for Names

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#267]
Names are in reverse order-first, middle, last on the 1850-1870 census, this is reflected in the help text but not the accompanying screenshot. Please update the image using this screenshot.Thanks
<img width="335" alt="1850-1870 census name help text screenshot" src="https://github.com/historyforge/historyforge/assets/57808782/8b90f3e8-3404-4331-9c64-f9c7b4bf666c">

**Comment by dfurber** [comment]
Done
