### ISSUE TITLE
census databases not able to filter on locality or race

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#270]
and probably other similar fields with check boxes
<img width="1111" alt="Untitled1" src="https://github.com/historyforge/historyforge/assets/57808782/9cb225cc-d372-4cc8-a47c-8306edecf6b2">

**Comment by EveSnyder** [comment]
Once you fix this I will check the filter options for race for each census to make sure that they display correctly.

**Comment by dfurber** [comment]
Oops!
