### ISSUE TITLE
1850 Census Test Drive

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#274]
@EveSnyder asked me to test drive the 1850 census.

(1) The 1850 census doesn’t have EDs or Sides.  We are using the FamilySearch image number for the “page” number.  But to get the “Mark 42 Reviewed” and the “Make 42 Persons” buttons, the program requires an ED. Can you remove that requirement for the 1850 census, so that we can do these two functions in batches?

(2) There’s no type-ahead/dropdown action going on in the Place of Birth field.  The controlled vocabulary feature is turned on, I can’t save invalid terms, so that’s good.  It’s just that I don’t get any help spelling Connecticut or Massachusetts, not even after entering them for the first time in 1850.

**Comment by EveSnyder** [comment]
Issue 2 is the same for the 1860 and 1870 census. Also, when trying it, I entered the abbreviated state and tried to save. The error message language needs to be changed, pob can't be left blank. That last part should reflect the instructions for adding new terms to the controlled vocabulary, something like:
  Pob is not yet in the controlled vocabulary. Please enter X in the Pob field and enter the Pob from the census in the notes field.
<img width="804" alt="Untitled1" src="https://github.com/historyforge/historyforge/assets/57808782/39a09676-8a4f-4fbb-86db-5e0a732c58c8">

**Comment by EveSnyder** [comment]
Sarah can you check issue 1 for the 1860 and 1870 census-I just finished a sheet from the 1870 census-to make sure it doesn't extend to these censuses.

**Comment by PatientRowan** [comment]
Batch buttons for Mark Reviewed and Make Persons do not work in 1860 and 1870.  Again, it’s because they don’t have enumeration districts.  I should have thought of this earlier!

**Comment by dfurber** [comment]
Fixed. Reopen as needed, with comments.

**Comment by PatientRowan** [comment]
All issues looking good to me, @EveSnyder, across all 3 censuses.  Thank you Dave!
