### ISSUE TITLE
Age help text 1850-1870 census data entry forms

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#275]
The help text for the below needs to be revised to the help text in the Census Label shared Google doc.
1850 census-Age (months)
1860 census-Age (months)
1870 census-Age and Age (months)

**Comment by PatientRowan** [comment]
(Close issue when published)

**Comment by PatientRowan** [comment]
I’m closing this issue as it seems to have been published as part of the Sunday, Nov. 5 package.
