### ISSUE TITLE
Can’t Make Space between Initials

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#276]
Uh-oh.  I heard from @EveSnyder  that you’d removed ending punctuation from Names.   I believe I am seeing an unfortunate result: all the names that should have a space between two initials, are now showing with the space closed up.
See Smith, Anna M W — now displaying as Smith, Anna MW on both census record and person record.  It won’t save with a space.

**Comment by PatientRowan** [comment]
Also, the program is not letting me make internal apostrophes.  I found this on an African American woman who gave her name to the enumerator as “U’wanda.”  This is a orthography we’d want to preserve.  
The “O’Hara” index LOOKS ok, but that is deceptive.  When I went to Alice O’Hara’s census record and changed her to O’Boyle, the computer took out the apostrophe.  I have changed her back to O’Hara but she displays now as OHara.
This is officially a serious problem now.
Note to self: fix Alice O’Hara and Uwanda Harris when possible.

**Comment by PatientRowan** [comment]
Related to Issue #272

**Comment by PatientRowan** [comment]
Oh no!  All the last name Van Gorder transcribed this Saturday are going in as VanGorder!

**Comment by dfurber** [comment]
Help is on the way.

**Comment by dfurber** [comment]
I fixed - and updated the Van Hoesen family in 1850 by way of testing. Please test and reopen if there are lingering bugaboos.

**Comment by PatientRowan** [comment]
Thank you.  All looks well.
This episode is causing me to harken back to a library computer feature that HistoryForge doesn’t need as such but which we might modify for our purposes?  Forgive me if I am describing something to you that you’ve already rejected, or if is unsuitable and a total non-starter, or not worth the trouble.

I think it might be good if HistoryForge searches on names automatically retrieved names that do not match the exact search query in the small matters of punctuation (such as apostrophes) and internal spaces.  I think HistoryForge is already capitalization agnostic.

The library thing, NACO normalization (or LSP normalization), is a form of behind-the-scenes massaging of personal names that make sure that all new headings going in are unique and not duplicates.  From this document: [https://www.itsmarc.com/crs/mergedprojects/helpauth/helpauth/dcm_z1_introduction.htm#NACO_normalization](url) : “The process of normalization removes all diacritics and most punctuation, and converts all letters to uppercase and all modified letters to their unmodified equivalents.”

More details: [https://www.loc.gov/aba/pcc/naco/normrule-2.html](url)

HistoryForge does not have a problem with duplicate headings, but it does have a problem with families that vary the spelling of their names.  The worst family for this, or at least I presume they are all related somehow, are the Van De Mark — Van Demark — Vandemark lineages.  Not to be confused with the Van Den Mark, Van Denmark, Vandenmark families, who also exist in Tompkins Co. but thankfully in smaller numbers.  There is, or was, variation in the VanBuskirks and DeCamps.  D’Amici and Damici.
When Eve and I were de-duping the person record index, we had to work from multiple indexes to bring all the manifestations of these families together and compare them.  If we had normalization working behind the scenes, any search with spaces on Van De Mark or Van Demark would have been converted to Vandemark and all three forms or the last name would have been retrieved at once.

**Comment by PatientRowan** [comment]
This example made me smile.  There’s a couple of Italian American guys who were enumerated as O’Cello in the 1930 census.  They’re really Ocello, as they were enumerated in the 1959 census.
