### ISSUE TITLE
Person Record Merge Broken?

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#277]
@EveSnyder and I both tried, independently.  We can’t merge Jane Johnson (maiden name; ID 149800) with Jane J Bradford (married name; ID 705).
![IMG_0508](https://github.com/historyforge/historyforge/assets/114665933/f855086e-1106-4472-a437-91e29b9b6128)

**Comment by PatientRowan** [comment]
It’s funny, I did a whole bunch of ordinary merges this morning and they all went through fine.  So I retried on this one—Jane Johnson -> Jane Bradford— and it’s still giving me this error message.  Could it have anything to do with her earliest appearance being on the 1870 census (from test drive)—maybe the merge is not set up to handle pre-1880?

**Comment by dfurber** [comment]
Something about Jane's marital status made the system upset. I'll look into it.

**Comment by dfurber** [comment]
Reopen as needed, with comments.

**Comment by PatientRowan** [comment]
Thank you, Dave.  She’s now all tied together across the years.  I really love your person record program—you can do complex things, but simply and elegantly.
