### ISSUE TITLE
One Photo to Multiple Addresses Broken

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#278]
I can't attach one photo to multiple addresses like I'm used to.  I type an address in the empty space, and nothing happens.  Doesn't work on the edit screen either.
I can patiently attach the same photo off multiple building records, so it's just an inconvenience, not impossible.

![Screen Shot 2023-10-20 at 11 00 37 AM](https://github.com/historyforge/historyforge/assets/114665933/00bfe84d-4f14-4355-acb6-213715112152)
![Screen Shot 2023-10-20 at 10 59 29 AM](https://github.com/historyforge/historyforge/assets/114665933/fc710920-c57c-4b99-b67a-282e80709ea1)

**Comment by dfurber** [comment]
Should be fixed now.
