### ISSUE TITLE
1850-1860 census should have Cannot read and write

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#283]
Please change the literacy question to:
Cannot Read and Write

**Comment by PatientRowan** [comment]
To clarify (for myself)—that’s “and” instead of “or”

not: Cannot Read or Write
Yes: Cannot Read and Write

It was an ampersand on 1850 and 1860 census forms, if you’d prefer.

**Comment by PatientRowan** [comment]
(Close issue when published)

**Comment by PatientRowan** [comment]
I’m closing this issue as it seems to have been published as part of the Sunday, Nov. 5 package.
