### ISSUE TITLE
1870 census-name order last name first

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#284]
The 1870 census modernized the names to Last, first, middle. Please update the field order and help text image to correspond (help text reflects last, first, middle).

![Untitled1](https://github.com/historyforge/historyforge/assets/57808782/d47fc0b8-1869-45df-b26e-693561c2527d)

**Comment by PatientRowan** [comment]
Sarah’s comment (as I wrestle through this for myself)—the help text is correct in HF, it’s just that the boxes are laid out in First-Middle-Last order instead of Last-First-Middle, and the help text image needs to be switched out to match.

**Comment by PatientRowan** [comment]
(Close issue when published)

**Comment by PatientRowan** [comment]
I’m closing this issue as it seems to have been published as part of the Sunday, Nov. 5 package.
