### ISSUE TITLE
problems adding photo to a person record

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#288]
We were able to attach photos to person records directly from a person record before but now it lets you add the photo from the person record, then it asks if it is a photo of a building, and then even if you say no, it goes directly to the map. It doesn't ask you if it's a photo of a person and it saves it to the photographs. I was able to go into the photographs and then save it to the person record from there, but that seems a little round about.

**Comment by dfurber** [comment]
Looks to me like that part of it was hooked up for buildings but never for people.
