### ISSUE TITLE
1950 Column References in Sample Line Income Questions

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#291]
I tried really hard, and @EveSnyder caught a lot of my mistakes, but I still haven’t got all the bugs in the help text for the 1950 census.  I am sorry to put you through this; at least it is small.  I would have tried to ignor the issue, except that yesterday a conscientious volunteer working at home read the help texts and moved her incomes around to the wrong columns based on the instructions.

For reference, here is the header on the census sample line for income:
![IMG_0543](https://github.com/historyforge/historyforge/assets/114665933/0b9d57b3-e9b7-4399-917f-e6997a01c852)

**Comment by PatientRowan** [comment]
Help text “31a” is correct for this box, no change needed:
![IMG_0537](https://github.com/historyforge/historyforge/assets/114665933/e14bbf12-51bc-476c-afb3-3026596b319c)

**Comment by PatientRowan** [comment]
Change help text to “31b”:
![IMG_0538](https://github.com/historyforge/historyforge/assets/114665933/1271fd50-f1ab-472e-a17e-932117554e01)

**Comment by PatientRowan** [comment]
Change help text to “31c”:
![IMG_0539](https://github.com/historyforge/historyforge/assets/114665933/a3afe5e0-6e0d-42b3-838c-0af08b618ce1)

**Comment by PatientRowan** [comment]
Change help text to “32a”:

![IMG_0540](https://github.com/historyforge/historyforge/assets/114665933/8e321425-d456-4f22-8c7a-dccced6280db)

**Comment by PatientRowan** [comment]
Change help text to “32b”:

![IMG_0541](https://github.com/historyforge/historyforge/assets/114665933/5a1a3a3c-6979-4650-b7c4-3d46f21d3568)

**Comment by PatientRowan** [comment]
Help text “32c” is correct, no change needed:

![IMG_0542](https://github.com/historyforge/historyforge/assets/114665933/0c35cc83-1305-45dc-95d6-6ea46e9add7d)

**Comment by dfurber** [comment]
This didn't actually get published because the disk was full. Please check again and close when satisfied.

Also the "fixed - not published" yet means I fixed it but haven't deployed it to the servers yet. Let's create a "reopened" label to signal to me that you reopened it.

**Comment by PatientRowan** [comment]
Still two little glitches.

31a is OK.
31b is OK.
31c is labeled “32c” — needs fixing.

32a is labeled “31a”—needs fixing.
32b is OK.
32c is OK.

**Comment by dfurber** [comment]
Fixed it.

**Comment by PatientRowan** [comment]
Cleared!  Wonderful.  Thank you.  I’ll notify the transcriber who told us about it.
