### ISSUE TITLE
Person Record Creation Not Working

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#293]
I am mystified.

Working on 1950, ED 36, Sheet 26.  It’s the second sheet I worked on today.  I did not have problems with Sheet 25.

Of the 24 records, I had made 1 by hand.  For the remainder, when I asked to “Make 23 People,” the computer merrily ran through the first 10 census records and created person records for them, then stalled out and told me “We’re sorry, but something went wrong.”

I tried sneaking up on the person records and making them one by one using the “Create New Person Record” button.  After multiple tries on some of the names, I was able to get all but 4 done: 

![IMG_0546](https://github.com/historyforge/historyforge/assets/114665933/9eb205db-168b-4156-89c1-0191a8fbb2b5)

This stubborn residue continues to tell me that Something Is Going Wrong whether I try to make them in batch or individually.

I don’t see an invalid character; I tried rebuilding the index in case it was getting full; I tried clearing my history.  All feeble efforts.

**Comment by dfurber** [comment]
The error suggests their name is too long. I’ll have to fix that.

**Comment by PatientRowan** [comment]
I’m glad you can see that something is up.  Thank you.

**Comment by PatientRowan** [comment]
I was just able to make all 30 persons for the next sheet, 1950 ED 36, Sheet 71.  The 4 missing persons on Sheet 26 are still failing.

**Comment by dfurber** [comment]
Actually it's not their name that is too long, but their "race", which is handwritten as "Latin American". That works for the 1950 census table which has no limit, but there is a (probably unnecessary) 12 character limit on the race column for the person table.

**Comment by dfurber** [comment]
Solution is obviously to remove that 12 character limit, which I am doing now.

**Comment by dfurber** [comment]
And reopen as need please.

**Comment by PatientRowan** [comment]
@EveSnyder says to reopen.

**Comment by dfurber** [comment]
The disk was full so it didn't actually publish when I thought it did. Please try again.

**Comment by PatientRowan** [comment]
Thank you!
