### ISSUE TITLE
Problem building development environment

### ISSUE THREAD

**Issue by mlppitt** [historyforge/historyforge#295]
I am trying to build a developer environment for History Forge.  I am having issues with the "bundle install".  nokogiri-1.15.3, pg-1.5.3 and sassc-2.4.0 all hang with the message "Building native extensions. This could take a while..."  What is a "while"?  I have left it running over night, and it doesn't make any progress that I could tell even though the Ruby interpreter appears to be doing something.  I am using my home laptop running Windows 11 and using cygwin.

While I have been developing software for many years, I have never used Ruby.  I thought it would be interesting to try and learn it, and maybe help out if you would like me to eventually.  I am currently working with an Angular client, Java services, Docker and a Postgres database in an AWS environment.  The concepts in Ruby seem pretty straightforward, but I am sure there are a lot of nuances.  I looked around a bit, but there were not many good suggestions for resolving the build problem.  I wondered if you might know what is going on, or maybe give me some suggestions since it is your codebase.

The commands I ran were:

- curl -sSL https://get.rvm.io/ | bash -s stable
- cd github/historyforge/
- rvm install "ruby-3.2.2"
- DEBUG_RESOLVER=1 bundle install --verbose

I originally just did "bundle install", but the extra parameters gave me more information.

I don't know if it is a correct thing to look for, but it looks like installed gems have a gemspec file in the specifications folder.  I could tell it was those 3 that hung, because they have a gems folder, but no gemspec file.

**Comment by mlppitt** [comment]
Got pg to install by running gem install on it which returned missing Postgresql path errors.  I added the paths, and it built.  The other two are throwing errors now, so there is at least something to investigate.

**Comment by dfurber** [comment]
If you want to run Ruby on Windows, I recommend using WSL2.

**Comment by mlppitt** [comment]
That did the trick.  The site is running locally.  Imported some data from Pittsburgh, but the default is Ithica.  Something else to play with over break.  It has been interesting.

I ran the tests  which failed complaining about Chrome, but I'll figure it out.

Thanks.

**Comment by dfurber** [comment]
Fwiw I think I had to install chrome within the WSL, as it couldn’t reach
outside to drive the windows installed browser.

**Comment by mlppitt** [comment]
I installed chrome and the chrome driver, and all the tests pass now
