### ISSUE TITLE
New Name Variants

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#302]
Not necessarily an action item, just a place to collocate discussion points.

—I notice that name variants are created instantly today.  Nice!

So here’s a place that the variant names are NOT created instantly:
—No match is offered, but you identify an existing person record as your person.
—You cut the existing person’s Person ID out of the person record and paste it into the Person ID box on the individual census record.
—No variant name is generated; you have to type it in by hand (which is not the end of the world)

**Comment by PatientRowan** [comment]
Interfiling.
There are two “Julia Abbott” in the database, both around the same age:
![IMG_0555](https://github.com/historyforge/historyforge/assets/114665933/ab168167-1b44-40c7-a725-5937d0d6319f)

![IMG_0553](https://github.com/historyforge/historyforge/assets/114665933/5897cac3-bab1-4d76-a23b-460e8e6c4d1c)

**Comment by PatientRowan** [comment]
The indexing does not make sense to me?  Is it because I was playing around with the Abbott/Shaheen names a lot?  Here is the woman who was Abbott in 1920, Sheheen in 1930, died 1935 a Barker (our rule is that we use the last name that was used *on a census* not the last name ever):
![IMG_0556](https://github.com/historyforge/historyforge/assets/114665933/c820e19c-f4c6-4390-93b8-aed3cb391c58)

This displays the interfiling that I was hoping for, but I think the presentation — plopped in the middle of the list with no clues about what it’s filing on or what the main name might be — is confusing.  

More importantly, why is the woman whose name was Julia Abbott throughout her lifetime falling the the very end of the index list? 
![IMG_0557](https://github.com/historyforge/historyforge/assets/114665933/be0319f2-adf4-46c8-93db-43ab9ef4802d)

**Comment by PatientRowan** [comment]
Match presentation.  I understand why this name is being presented to me twice, but it looks so confusing!
![IMG_0552](https://github.com/historyforge/historyforge/assets/114665933/cc10c4ff-98ba-4cb7-9589-4fc2249e2fbb)

**Comment by PatientRowan** [comment]
In my old job we’d call these variants “Sees.”  As in “Abbott, Julia _see_ Sheheen, Julia.”  The italics were a universal convention.  Modern online catalogs sometimes still use the word “See” but they also gray out the type on the variants and keep the main names in bold.

**Comment by PatientRowan** [comment]
The name matching algorithm is still weaker than I’d like.

1940 census: Spencer, Phyliss — age 4

Not offered as a match with:

1950 census: Spencer, Phyllis — age 14

I’ll probably correct the spelling of the header to Phyllis later but I wanted to show what the algorithm stared with.

**Comment by PatientRowan** [comment]
1930 census: Slattery, Ethel — age 30

Not offered as a match with:

1950 census: Slattery, H Ethel — age 51

Program should be first/middle name agnostic

**Comment by PatientRowan** [comment]
Name header: Louis B Roe — born 1898
1920 census: Roe, Louis B — age 21
1950 census: Roe, Louis — age 52

Not offered as a match with:

1910 census: Roe, Lewis — age 12

The old algorithm knew about Louis/Lewis

**Comment by PatientRowan** [comment]
1950 census: Van Demark, Ray B — age 65

Not offered as a match with:

1910 census: Vandemark, Ray B — age 25

Illustration of the problem with presence or absence of spaces within names.  In systems I have worked with before, the problem is helped by “normalizing” the name by closing up any spaces within the name as Step One in performing a search.

**Comment by PatientRowan** [comment]
1910 census: Patch, Horace E

Algorithm offers as a possible match:

Potter, Roland

I don’t see anything on Roland Potter’s record that could introduce the Horace Patch concept.

A few lines later on the 1910 census:

Landon, Sextus B

Algorithm offers as a possible match, the same Potter guy:

Potter, Roland

**Comment by PatientRowan** [comment]
Newly created person records are not indexing in alphabetical order.
I’m not sure how often.
![IMG_0559](https://github.com/historyforge/historyforge/assets/114665933/bd101f94-a862-41a3-9241-2e8cb29c9101)

**Comment by PatientRowan** [comment]
Heading: Samuel J Schaeffer
1930 census: Schaeffer, Samuel J — age 28
1940 census: Schaeffer, Samuel J — age 38

Not offered as a match with:

1950 census: Shaeffer, Samuel J — age 48

Same for his wife Marion G Schaeffer/Shaeffer and daughter Helen.

**Comment by PatientRowan** [comment]
Heading: Francis J Kane
First name Francis for census years 1900-1940

Not offered as a match with:

1950 census: Kane, Frank J

**Comment by PatientRowan** [comment]
Could it be that the capital W is throwing it off?

1850 census: Garrett, Dewitt C — age 31

Not offered as a match to:

1870 census: Garrett, DeWitt C — age 50

**Comment by PatientRowan** [comment]
1880 census: Kellogg, Lavinia — age 36

Not offered as a match with:

1870 census: Kellogg, Lavina — age 27

**Comment by PatientRowan** [comment]
1950 census: Beach, Stacey — age 56

Not offered as a match with

1940 census: Beach, Stacy J — age 46

**Comment by PatientRowan** [comment]
1940 census has Glazier, Lilian — age 60
Offered as matches: Caroline Potter, Bertha Potter.
NOT offered as a match:
Glazier, Lillian (1950 census) — age 70

Geez.

**Comment by PatientRowan** [comment]
1920 census: Quick, Frank — age 27

Not offered as a match with:

1910 census: Quick, Frankie — age 17

It’s not unreasonable to ask for this match, is it?

**Comment by PatientRowan** [comment]
A sample of today’s mystery matches:

Newly transcribed: Jordan, Franklin
Offered as a match: Henry J. Grant

Newly transcribed: Lewis, Emma R
Offered as a match: Bina VanDenbergh

Newly transcribed: Jordan, Franklin
Offered as a match: Henry J Grant

**Comment by PatientRowan** [comment]
A transcriber working on 1940 Dryden entered a man whose name was “Marion, Russell” [Last name, First name] as Marion Russell [First name, Last name] in HistoryForge.  Transcribers do this more than you’d think.

The current algorithm did not offer me a match with the existing Marion, Russell I [https://tompkins.historyforge.net/people/182025](url)

I think it’s important for the program not to consider whether the name elements being matched appear in the first, middle or last name fields.

This is a variation on my complaint above about Ethel Slattery not matching with H. Ethel Slattery.

I know I’m whining again, but the old program go this!

**Comment by dfurber** [comment]
I tweaked it a bit. Let's see how it goes.

**Comment by dfurber** [comment]
Closing because we've continued the quest in other issue tickets.
