### ISSUE TITLE
Editing Variant Names Can Cause Error Messages 

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#303]
I need to delete Person ID 28017 but it is lost to access for me.  The record was for Richard LaFrance, age 10 in the 1930 census and living on Center St.  Could you delete it for me?

I’ve been adding variant names for about a week now, and this has happened to me several times: I add a variant name and want it to be the heading (main name), so I click off the first box and click on the variant name box, and then, I don’t know, I make some edits in the name fields, and then I try to save.  I get an error message.  Sometimes it seems it’s because I’m working too fast or making too many changes at once before saving, but I don’t really know why it happens.  In all cases except ID 27017, I’ve been able to use the back button to a safe place and proceed more cautiously without further problems.

On Sunday, Jan. 7, I was working on a Richard LaFrance.  His heading was “Richard LaTrance” with a variant for  LaFrance.  As far as I could tell, LaTrance was never used on a census.  I wanted to delete the LaTrance variant.  I clicked around some, probably in the wrong sequence, and got the error message.  I then tried to retrieve the person record that I had messed up, but I couldn’t access it off the census record it was related to in the 1930 census.

I fixed it, sort of, by using a new person record 197910 off the 1950 guy and using it on his 1930 census record.

**Comment by dfurber** [comment]
It looks like you managed to delete all of his name records, so now he is a nameless dude.

**Comment by dfurber** [comment]
Funny you can see the person record when you're logged out, but not after you log in.

**Comment by PatientRowan** [comment]
I obviously completely lost my head, but I imagine I might have been frantically editing variant names, unchecked all the boxes as neither primary nor variant, and then tried to save the record.

**Comment by dfurber** [comment]
I fixed the error, and discovered that Richard LaFrance was left without a main name. I made his name is primary name again.

**Comment by PatientRowan** [comment]
That’s good.  I have merged the person record that you rescued onto the the person record that I created to paper over my mistake, ID 197910.

I have pointed this out before, but as we add more variants, the incorrect indexing of the names becomes ever more of a problem.  I wanted to check the two records against each other under filter last name LaFrance, expecting LaFrance Richard that you handled to be followed by my LaFrance Richard Paul (ID 197910).  But the index is out of order so it is harder to detect dupes now:
![IMG_0568](https://github.com/historyforge/historyforge/assets/114665933/7b04c21f-623a-41d6-a9fe-387771d8ddd0)
(I should say, this screenshot is after I performed the merge, so the second Richard LaFrance is not present in this index).

@EveSnyder you have probably started to see this too—

**Comment by dfurber** [comment]
I think that is part of the other issue, so closing this one.

**Comment by dfurber** [comment]
I do see that there is a second trance of "LaFrance" out of order, beneath "Loading more records". Not sure why, perhaps worth its own issue.

**Comment by dfurber** [comment]
I see what the problem is though. Will fix it when I can. The name is no longer on the person record but in the associated names. But I didn't clear out those columns when I migrated to name records. So the name ordering is using the name on the person, which would be null for new person records since I added the name feature. I have to make it order by the primary name.

**Comment by PatientRowan** [comment]
Thank you for working on the holiday.  I’m going to post some “new” issues that are just bite-sized versions of this thread.  I’ll keep working with the program and let you know how it seems.  Today (1/16) I have less time than I would like to play around.

**Comment by PatientRowan** [comment]
I have some tangentially related issues that I am going to add to Issue #310 but this particular mess I got myself into, you have fixed.
