### ISSUE TITLE
user account set up problems for Walnut Hills-*priority

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#304]
JoAnn from Walnut Hills is having trouble creating user accounts for her four interns who start tomorrow afternoon. Two of them didn't receive the email with the link to create their account. In at least one case the link sent someone to a page but they weren't able to set up the password from there. She does not have the specifics and could not replicate that to get them.
She then tried to set up a new account with a different email. Here's what she found:
1-The email isn’t being sent. (waited 5 min)
2-Clicking the Password box on the view user page does not send an email. (again, waited 5 minutes)
3-In Edit User, I COULD enter a password, confirm & save, and then log in with that email & password. BUT I could not duplicate that behavior with one of the intern’s emails.
Any suggestions?

**Comment by dfurber** [comment]
Maybe it hits their junk folder?

**Comment by EveSnyder** [comment]
That was the first thing I asked before she sent me the above.I was able to set up a test account using one of my other email accounts but that doesn't solve the problem.
