### ISSUE TITLE
Mystery Matches

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#306]
The new program has these weird mystery matches.  The same folks’ names are irrationally suggested over and over.  There’s Bina VanDenbergh for women; for men, this is a common one, with two matches suggested, neither making any sense:
![IMG_0573](https://github.com/historyforge/historyforge/assets/114665933/92df4223-2097-4f08-a618-a8c1d7d7646b)
It’s obviously going off age, but it’s still so weird.

**Comment by dfurber** [comment]
That's because I'm an idiot. But a fix is on the way. I hope the matching is satisfactory.
