### ISSUE TITLE
Latest Iteration of Person Record Matching Algorithm

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#310]
This is not an (immediate) action item, but I want a place to park examples of non-matches.  It still kinda sucks.
The first name I give below is the already-existing person record header.  The second name is the one I’m working on, asking for match suggestions.

1920 census: Heath, Dortha W — age 10
Not offered as a match with:
1910 census: Heath, Dorothy W — age 0y 10 mo

1950 census: Homer, Anne E — age 28
Not offered as a match with:
1940 census: Homer, Ann — age 38

**Comment by PatientRowan** [comment]
1920 census: Gee, Marjorie — age 14
1930 census: Miller, Marjory E — age 25
1940 census: Miller, Marjory — age 35
1950 census: Miller, Marjorie — age 45
Heading: Miller, Marjory

Not offered as a match with:
Gee, Margery L — age 5

I think that between the 1920 Gee xref and the similarity between Marjory, Marjorie and Margery, the algorithm ought to be up to this one.

*Is it possible that the algorithm is comparing only against the header Miller, and not also against the variant list that included Gee?

**Comment by dfurber** [comment]
Thanks for the examples. I think I figured out why it went crazy, and hopefully fixed it.

**Comment by PatientRowan** [comment]
Before complaining more, let me say how thrilled I am that this match worked wonderfully:

I’m asking for a match on Mary K. Caveney, age 1 year 3 months, 1910 census.
The algorithm offers me Mary Alexander.
I say HMM
Yes indeed—she was Mary Caveney for the 1910, 1920 and 1930 censuses, then married and appears in 1940 and 1950 as Mary Alexander.  (Regrettably, the marriage does not appear to be a success—spouse not present in 1940, separated in 1950).  I say yes to the match!

This answers the question I had earlier about whether the matches were being made against only the header, or against all the variants as well.  As one would hope, the variants are part of the equation.

**Comment by PatientRowan** [comment]
Also thank you for creating the variant names when performing a merge.  I merged Fern Turk (birth name) with Fern Marshall (married name) and did not have to type in the variants.  Though I did clear out a couple of variants with middle initial variations that I think of as inessential.

**Comment by PatientRowan** [comment]
Complaints dept. for the day:

Existing header: Fannie V Miller
1920 census: Miller, Fannie V — age 52
Not offered as a match with:
1910 census: Miller, Fanny V — age 42
[She is Fanny, not Fannie, in Find-a-Grave, so I have changed her header to Fanny].

1920-1940 census: Turk, Theodore
Not offered as a match with:
1910 census: Turk, Teddy

**Comment by dfurber** [comment]
> Also thank you for creating the variant names when performing a merge. I merged Fern Turk (birth name) with Fern Marshall (married name) and did not have to type in the variants. Though I did clear out a couple of variants with middle initial variations that I think of as inessential.

I do wonder if I should filter out middle initial for variants. Add it if it's not there, but don't create a new variant unless it's a different middle initial from one that's already there.

**Comment by PatientRowan** [comment]
I think that sounds right about the middle initials.  @EveSnyder ?

Schenectady is reporting mystery matches.  Of course it doesn’t really matter because they should not have any true matches, but they see suggested matches already in their first census year, and it is the opposite of confidence building.  Do they have the latest version of the matching program?  Because I think you have solved the mystery matching problem (Issue #306) although I have not seen enough to be sure about that.

**Comment by dfurber** [comment]
When diagnosing Teddy Turk, I found that it was only properly matching the girls on first name cognates. You can see the list of supported cognates here: https://github.com/historyforge/historyforge/blob/master/app/services/people/nicknames.rb. If you See any missing, LMK.

**Comment by dfurber** [comment]
As for Schenectady and the mystery matches, I juggled the algorithm a bit so that if it finds no exact matches (last name trigram + exact match on first name cognates), it falls back to a combined list of last name trigram matches and trigram matches on first name cognates and last name combined. But I see the point that Schenectady would see them as "mystery matches" because the program doesn't know that you have only one census going.

**Comment by PatientRowan** [comment]
> When diagnosing Teddy Turk, I found that it was only properly matching the girls on first name cognates. You can see the list of supported cognates here: https://github.com/historyforge/historyforge/blob/master/app/services/people/nicknames.rb. If you See any missing, LMK.

That is fantastic, Dave, thank you.  @EveSnyder keep this in mind!

**Comment by PatientRowan** [comment]
> As for Schenectady and the mystery matches, I juggled the algorithm a bit so that if it finds no exact matches (last name trigram + exact match on first name cognates), it falls back to a combined list of last name trigram matches and trigram matches on first name cognates and last name combined. But I see the point that Schenectady would see them as "mystery matches" because the program doesn't know that you have only one census going.

@EveSnyder You might want to report this back to Schenectady, at least, once they have the newly juggled algorithm.

Edited to add: Schenectady is not reporting the fact of matching as a mystery.  They’re seeing matches that seem remote:  a match on first name John or William, with completely different last names.

**Comment by PatientRowan** [comment]
I have one Mary Bouvier to work on, and a match is offered to Mary Bovier:
![IMG_0588](https://github.com/historyforge/historyforge/assets/114665933/085b1197-59be-4544-b9e6-73981a2a6a43)
So I check against the census sheet itself, and sure enough, it really is spelled Bovier, not Bouvier.  I correct Bouvier to Bovier, expecting to retain the suggested match.  But it has vanished:
![IMG_0589](https://github.com/historyforge/historyforge/assets/114665933/681b1362-9464-448b-92e2-fc9865199cb8)

**Comment by dfurber** [comment]
Bovier's problem is that there were 11 "exact matches" but the query was limited to 10, and the correct record was number 11. I've removed the limit for exact matches. (The query returns name matches but then filters out the matches with more than a 2 year age difference.)

**Comment by dfurber** [comment]
Why there were 11 exact matches on "Mary Bovier" is a different question. Something about Mary, I guess. Actually, the reason is that "Bower" is a trigram cognate of "Bovier" but not "Bouvier".

**Comment by PatientRowan** [comment]
That’s interesting.  Those trigrams are a dark force in the HistoryForge universe.

**Comment by EveSnyder** [comment]
> > Also thank you for creating the variant names when performing a merge. I merged Fern Turk (birth name) with Fern Marshall (married name) and did not have to type in the variants. Though I did clear out a couple of variants with middle initial variations that I think of as inessential.
> 
> I do wonder if I should filter out middle initial for variants. Add it if it's not there, but don't create a new variant unless it's a different middle initial from one that's already there.

I agree, middle initials offers little value, they seem to be incorrect a good amount of the time. Sometimes its enumerator error, and other times it's because they are hard to decipher especially when written in cursive, even for those of us who know how to read cursive.
I think expanding the range of birth years from +/- 2 years of dob based on the census might be more valuable for matching purposes, but I'll defer to Sarah on that since she's been matching the people off the hints and I have not. I will say that when I'm in the person database, if a person record looks like it could be a match for another person record and the birth years are 10 and even occasionally 15 years apart, I check the records manually to see if they have the same other family members and its happened enough that they match that way that I'm going to continue.

**Comment by PatientRowan** [comment]
Jan. 28:
1910 census: Besemer, Leland — age 14
Not offered as a match with
1900 census: Besemer, Leeland — age 4

**Comment by dfurber** [comment]
Looking into the middle name variant stuff, I wonder if I should just remove prefix, middle name, and suffix entirely from the person name / name variants thing.

What I've been looking at is to run through all the names, and if the first and last name are the same as the primary name, then if there's a middle name or prefix or suffix, merge those into the primary name, and then delete the variant. That means that a "John Smith" might become a "John G Smith" but a "John G Smith" would not become a "John C Smith". Similarly, a "John Smith Jr" plus "Dr John C Smith" would become "Dr John C Smith Jr".

If we drop middle, prefix, and suffix for person names, then when you search for "dr john smith" on home page, it wouldn't know about the "Dr" bit.

I'll leave it for now and let's keep discussing.

**Comment by dfurber** [comment]
Some further thought:

* The person's primary name should be part of the person record, and have all the parts.
* The name variants should only be first and last name.
* When connecting a census record to a person, have it fill in blank parts - so if there is no prefix, suffix, or middle name yet on the primary name, it would fill in from the census record. But it wouldn't change or remove existing parts. And it would add a name variant only if the first or last name are different.

**Comment by dfurber** [comment]
@EveSnyder @PatientRowan I just pushed the above fix. I made a copy of the database before I ran it in case we need to go back. So please test it out before you do a lot of work on the database. Not particularly worried just being careful. It's looking great to me.

Note that now a person record has the full name, and is considered the canonical name. Then there are name variants, which are first and last name only. Under the hood there is also a "variant" that is the canonical name for sake of performance, but you shouldn't see it exposed. (LMK if you do see it.)

Now the "duplicates" that I see on the person records appear to be genuine duplicates in need of a merge. If you see 2 of the same person record and one is not a "see", LMK please.

**Comment by dfurber** [comment]
I also boosted the "age similarity" range from 2 to 5 years, and add a trigram match on the given first name. That makes Leland and Leeland match. I hope that between that and the first name cognates, we are set.

**Comment by PatientRowan** [comment]
I’m sorry I didn’t reply last night.  I wasn’t ignoring you, I was excited in fact, but the whole Sunday dinner thing with my mother takes a lot out of me.
One thing I was worried about last night, before you implemented your ideas, was that we’d get hung up on the whole “canonical name” principle.  It’s absolutely necessary in traditional library catalogs, but I want to avoid having volunteers arguing about the form of the “perfect” name and difficult rules.  As long as you can get from one name to another and find all your info in one place, that has to be good enough for a database our size powered by volunteers.  
But when I see what you’ve actually implemented, it’s definitely a big improvement.  The indexes are so much cleaner.  Right, @EveSnyder ?  I haven’t yet seen any variants that I care about removed.

**Comment by PatientRowan** [comment]
I was slightly confused by how to drive the canonical/variant name changes I wanted to make.  It might take me and @EveSnyder some practice to get the hang of it.

Working on a family where the parents of the young Gordon Stark(e) were spelled Stark, but Gordon himself and his wife Constance have Find-a-Graves spelled Starke.  [It’s irrelevant, but I read in the Ithaca Journal that Gordon Starke, spelled Starke there too, killed himself in his car with carbon monoxide exhaust].  I wanted to make the 1950 Gordon Stark family canonical Starkes, with Stark as a variant for all of them.
First, I tried to type in Starke as a variant, but quickly saw that you have taken away the check box that made one name Primary and marked the others as variant.

![IMG_0591](https://github.com/historyforge/historyforge/assets/114665933/1451d548-ac01-4fdc-95e1-e0e98c21e46f)

So the way to go is to edit the canonical name right off and see what you get:

![IMG_0592](https://github.com/historyforge/historyforge/assets/114665933/2444766e-5bd5-4e52-a8c3-d5bd8d5a3908)

As you can see I was balking at the omission of the the middle name.  The program let me input “Julie Ann” as a first name, but it was still grabbing plain “Julie” to add as a variant:

![IMG_0593](https://github.com/historyforge/historyforge/assets/114665933/d33a6b65-477e-4150-b80d-c6c6c0886c24)

I zapped the xref for “Julie Stark” but that is not the aim of the current program.

I wonder if it would be OK to leave your program as it is, but allow us to tinker on the margins?  I don’t have examples right to hand, but I have seen people who are enumerated as E. Jean Carroll in one census year, Elizabeth J. Carroll in another, and Jean E. Carroll in a third.  For indexing purposes, they’ll all take you to the same canonical name, but the explanation of how they are all the same person is clearer if the middle element is preserved.

I hope I do not sound carping.  I recognize what a huge achievement this is, and cannot thank you enough!

**Comment by dfurber** [comment]
The Julie Ann problem is simple. You've got the canonical name as "Julie Stark" with "Ann" as the middle name. But the variant has "Julie Ann" as the first name, which is not equal to "Julie". I currently only see "Julie Ann Stark" as a name variant, perhaps because you deleted "Julie Stark".

I think I have a way around this conundrum. Instead of hiding the name variant only if it shares the same first and last name as the canonical name, I've also added a comparison to the full name. Thus "Julie" "Ann" "Stark" will compare to "Julie Ann" "Stark".

**Comment by PatientRowan** [comment]
Yes, it was I who made Julie Ann a first name and removed xref Julie Stark, in an effort to work the system.  I’m not sure if your message above is giving me permission to use this method, or nixing it?  It does not seem like a good idea to me but I was giving it a try.

Part of the problem is vocabulary: I think of what you call the “canonical name” as the name in bold at the head of the record, in this case Julie Ann Starke.  But you seem to be saying that the canonical name is only the first and last name elements of the name on the header.

I had a guy today who was enumerated as Herbert Jackson but achieved a modest level of fame as H. Merrill Jackson:
![IMG_0611](https://github.com/historyforge/historyforge/assets/114665933/aaa6dc9d-a18b-48dd-8265-9a1a60307a98)

With this middle element in flux, I added name variants for both H Jackson and Merrill Jackson, but did not try to add a “first name” of H Merrill.  Is that a better way to go?  We don’t have a match to be made on his name, so it’s harder to tell.

**Comment by dfurber** [comment]
Almost. The canonical name is indeed what is in bold on the header.

But the canonical name also has a matching "name variant". And "name variants" only have first and last name. If I add back middle name, we are right back in the soup we just got out of, for an edge case.

Thus I'm okay with your solution, and coded it so that if the first + last name of the name variant = the entire canonical name, it doesn't list it under name variants on the detail page.

Not sure what to do about Herbie, other than that the canonical name ought to be "Herbert Merrill Jackson" and forget about the H as first name. If the census record auto-added a name variant for H Jackson, it can be deleted. Or expand its first name to "H Merrill". 🤷‍♂️ Not sure how much agonizing it is worth.

**Comment by PatientRowan** [comment]
That’s great!  I am hearing that any solution I might choose won’t break the system, and No Agonizing Allowed.  I am closing this issue.   Thank you for your patience and skill working it through.
Could I prompt you to push this version out to the other partners so that they stop complaining about weird-looking matches?
