### ISSUE TITLE
Additions to Person Matching Cognates List 

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#312]
Please add:
Chas to Charles
Wm to William
Ellin to Ellen

(I had a Chas and and Ellin this morning)

**Comment by PatientRowan** [comment]
And from a few days ago

Marjory, Marjorie, Margery, Marge

**Comment by PatientRowan** [comment]
Add to Louis-Lou-Louie: Lewis, Lew
And to both Francis and Franklin: Frankie
Add to Dorothy: Dorothea
Add to Elaine [which already has a lot of Eleanor variations]: Eleanore, Elenore

Question.  An earlier example of mine did not match Stacey and Stacy (man’s name).  I also had a Phyllis and a Phyliss.   I don’t know what a “trigram” is, but it seems to me that those names are either mis-spellings or some kind of alternate spelling.  Do they have to be on the cognates list, or are they close enough to get picked up as trigrams?

**Comment by dfurber** [comment]
I added these things. And can say that, for the "exact match" that it trigrams the last name, but not the list of first names. Reason is that I'd rather build up a good list of first name cognates, and not combine that with trigram because performance on so many matches is terrible relative to the gain from the trigrams.

**Comment by PatientRowan** [comment]
Does that explain Stacy/Stacey, Phyliss/Phyllis, and today’s Leland/Leeland?  There seem to be an awful lot of these near misses that I think ought to be recognizable.
I know I don’t understand this, but is there any way that an exact match on a last name, when it hits a near miss on a first name, with age within 2 years, can trigger a suggested match?  Would that be a conditional trigramming on the first name?
The reason I’m being resistant is that it was a lot better—delightful, really—for the first year and a half.

**Comment by dfurber** [comment]
It does explain them. Despite my comment from yesterday, I went on to tweak the algorithm so that for first name it does a trigram search on the first name as entered OR an exact match on a known cognate.

**Comment by dfurber** [comment]
A trigram would never match Chas with Charles. So if you find more legit cognates that aren't in the list, please reopen this issue and add them as a comment.

**Comment by PatientRowan** [comment]
Working on the 1870 census, the enumerator routinely uses abbreviations like Chas and Wm.  Please add:
—Geo for George
—Benj for Benjamin (there’s some other nicknames for Benjamin, but not this one)

**Comment by PatientRowan** [comment]
Please add to Edwin : Eddie
Edwin has Ed, but not Eddie or Eddie; Edward has Eddie and Eddy
—I was working on Edwin D Johnson, called Eddie when he was 7 and Edwin at age 17.

**Comment by dfurber** [comment]
I've added the additional cognates.
