### ISSUE TITLE
Tompkins.historyforge.net shows Walnut Hills

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#322]
I tried getting at Tompkins various ways, but still have not yet been able to sign in.
![IMG_0615](https://github.com/historyforge/historyforge/assets/114665933/46401b16-184d-4088-a267-5abbf4cf75f6)

![IMG_0616](https://github.com/historyforge/historyforge/assets/114665933/4fada53b-234b-4d7e-a62a-2f351ba87a0f)

**Comment by dfurber** [comment]
This is more of a "text me" problem than a GitHub issues problem...

**Comment by PatientRowan** [comment]
And maybe birth month too?

**Comment by PatientRowan** [comment]
Sorry, wrong issue.
