### ISSUE TITLE
Add Kathryn to cognates for Catherine

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#323]
I see this cluster of names relating to Catherine on the cognates list:
 %w[Catherine Cathleen Katherine Kathleen Cathy Kathy Katy Cassie Kay Kit Kittie Trina Lena],
But it lacks **Kathryn**
![IMG_0631](https://github.com/historyforge/historyforge/assets/114665933/4a595f61-6d2b-495d-b86b-0df4273c1e03)

I made the match by hand:
![IMG_0633](https://github.com/historyforge/historyforge/assets/114665933/d7e7bf73-ae3e-4b8b-81dd-5fc2e843eb80)

**Comment by dfurber** [comment]
Go Kathryn!
