### ISSUE TITLE
Photograph records lack caption & description

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#325]
I regret that I have caused a mess by involving myself in community-supplied photographs.  I was an idiot.  Later today I hope to meet with @EveSnyder and start the Cleanup on Aisle Five.
I see you have been tinkering with the photograph records.  Did you make the captions & descriptions invisible (except in edit) until this cloud blows over?
![IMG_0646](https://github.com/historyforge/historyforge/assets/114665933/318b2c41-698e-4ec0-826d-deca6fc44a74)

**Comment by dfurber** [comment]
After my house became famous, I spent a moment cleaning up this page. Looks like it got too clean.

**Comment by dfurber** [comment]
Yeah I hid a bunch of stuff while trying to get it to look good on mobile, and forgot to unhide it. 😞

**Comment by dfurber** [comment]
Reopen as desired, but seems fixed.

**Comment by PatientRowan** [comment]
After my house became _[**justly**]_ famous 
I’m looking forward to the 1950 census getting to Crescent Pl.  Those tax photos went in before we got to South Hill on the census, so all the records lack inhabitants.  It’s going to be fun to see all those neighbors.
