### ISSUE TITLE
Mystery We're Sorry messages

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#326]
I don't know how I saved 1870 William Parr, apparently without a Dwelling and Family number, but now when I click on his record to add the numbers or delete him and start over, I get a We're Sorry message.
[https://tompkins.historyforge.net/census/1870/470](url)

**Comment by PatientRowan** [comment]
That's weird.  I left William Parr alone and input his wife Hannah Parr on the next line.  When I try to open Hannah's record now, I get another We're Sorry message.  [https://tompkins.historyforge.net/census/1870/471](url)
Their lodger George F. Webb is opening as usual.

**Comment by PatientRowan** [comment]
For no reason that I am aware of, newly input Anna Williams [https://tompkins.historyforge.net/census/1870/489](url) is also We're Sorry (500) this morning.

**Comment by PatientRowan** [comment]
Aha.  I think the problem is a change in my habit in the 1870 census.  I usually save using the pull-down menu selecting prefills for the next record.  However because I find the 1870 census difficult, I have sometimes been just hitting "Save" without a pulldown choice, planning on immediately proofreading and editing the record.  Saving the record that way seems to be causing the We're Sorry message.
Looking at baby Charles Pickering: [https://tompkins.historyforge.net/census/1870/496](url)

**Comment by PatientRowan** [comment]
Maybe my theory is wrong.  I did not save Stella Crozier without selecting from the pulldown menu for the next record, but I'm still getting a We're Sorry message for her record: [https://tompkins.historyforge.net/census/1870/504](url)

**Comment by dfurber** [comment]
I think it's marriage month. Fix will be along shortly.

**Comment by PatientRowan** [comment]
Sorry I had posted to the wrong issue.  I seem to remember that Charles and Stella had birth months.

**Comment by dfurber** [comment]
This fixes the problem that generated the error logs associated with this issue.

**Comment by PatientRowan** [comment]
Looking good, thank you.  In making my corrections, I discovered that I had been mistakenly entering the babies' birth month in the marriage month menu--a good tip for the future.
