### ISSUE TITLE
Over-Matching on First Name Only

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#327]
Algorithm matches on first name, sex & age range, but last name is unrelated to the target person.
Walnut Hills is reporting this issue via @EveSnyder.  I can’t say how often Walnut Hills sees it.  I see it on a small scale in Tompkins Co. but nothing that bothers me, in fact with married women’s name changes it is a positive benefit.  
![Untitled1](https://github.com/historyforge/historyforge/assets/114665933/0103bad6-2f74-43be-bac9-113e9a4a431b)
![George Farren WH HF](https://github.com/historyforge/historyforge/assets/114665933/aa597e4a-bbc7-40ba-ba49-0d67395a6a58)
![Caroline Farren-WH HF](https://github.com/historyforge/historyforge/assets/114665933/05beebd4-4aa3-432d-a3c9-08d40951fb2e)

**Comment by EveSnyder** [comment]
Dave can you confirm that Walnut Hills (and the other partners) are using the same version of the matching algorithm as we are? Some of the other installations, like Walnut Hills, have data entered from more than one census and are ready to test the matching algorithm.

**Comment by dfurber** [comment]
All HF use the same algorithm. I take "first name only matches" to mean "if it's a man, it's probably a new person, if it's a woman, then check for married name". We could change it to do this only for women, if you haven't found it helpful for matching men with inconsistent name spellings.

**Comment by PatientRowan** [comment]
I like the current version.  I do not understand the black box of how it does its work, but it does find matches that can be nothing you would have thought of without its help.   I mean, you never know when an apparently unrelated last name is going to be the key that unlocks a weird family tangle. I don’t find the number of complete “nuisance” suggestions (if I may call them that) to be a problem.  Perhaps we could tell JoAnn that we agree she is seeing a real phenomenon and that we’ll all keep an eye on it?

**Comment by PatientRowan** [comment]
I like our current name matching, but I also just don't get it.  When do the first-name-only match suggestions kick in?  My current impression is that they're not commonly offered.

 Yesterday I reviewed a 1950 record for the president of IC, Leonard Job, living at Fountain Place.  The name on the census seems clear to me as Job, but it is understandable that the transcribers entered "Jones":

![Screen Shot 2024-03-21 at 7 43 45 AM](https://github.com/historyforge/historyforge/assets/114665933/2f3a511c-a47f-47ff-ab64-b5109f51b17d)

![Screen Shot 2024-03-21 at 7 48 42 AM](https://github.com/historyforge/historyforge/assets/114665933/75a74279-1916-4dda-88cc-9f9f479593d1)

When I first saw the record entered as Leonard Jones, no match was offered.  (Or possibly there was a match, but not a relevant one--I can't remember).  I have no idea what a trigram is, but it seems like it could have something to do with needing at least 3 letters to suggest a match.  Only two letters match between Jones and Job.  This is a rule I can deal with.  But why didn't the algorithm in this case offer me other Leonards in the right age bracket, presumably including Leonard Job?  I changed the last name to Job and of course was immediately offered the match.

![Screen Shot 2024-03-21 at 7 53 36 AM](https://github.com/historyforge/historyforge/assets/114665933/b8fd1d62-28ef-463b-9f75-a42a8b56a420)

**Comment by dfurber** [comment]
It only does "fuzzy" matching (meaning, allow a first name match within the same age range without a last name match) if there are no "exact" matches (meaning, first and last and age range). Both variations account for name cognates. So if it's offering first name matches, then there are no exact matches. Maybe I should update the form to indicate such.

**Comment by dfurber** [comment]
I've done this, although you won't see it until I've removed the "fixed - not published yet" label. If the matches are "fuzzy" rather than "exact", there will be a sentence that says not to put too much stock in the recommendations.

I also added race to the criteria, so that you won't get W matches for a B person, and vice versa.

**Comment by PatientRowan** [comment]
OK, I see the language: "No exact matches. Showing possible (but usually unlikely) matches." Please forgive me for wordsmithing -- but given how Walnut Hills wants all matches to be automated -- could you change the wording to "No **close** matches [etc.]"? I'd like some waffle room.

@EveSnyder -- matching on race worries me.  Of course it's sometimes exactly the definitive difference, but it strikes me as risky.  We have seen people who are white on one census and something else on other censuses.  It's not necessarily determinative.  Also, have you accounted for all the ways to say people were Black/Negro/Mulatto in different censuses?

**Comment by PatientRowan** [comment]
I like the label for the less-likely matches.  I'm getting random Ethels and random Coopers but none of them is Ethel Cooper.  With your label, I'm less invested in getting one of them to work.
