### ISSUE TITLE
Delete “Institutional Work” Column in 1940 Census

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#329]
I have been trying to ignore this problem since we did 1940 Ithaca a long time ago and nobody has had a problem since.  But a new volunteer starting working on 1940 Dryden and she had trouble checking off the correct column, so I’m reporting it now.
There are four yes/no employment questions on the 1940 census, Columns 21, 22, 23, and 24, followed by the No Work Reason:
![IMG_0617](https://github.com/historyforge/historyforge/assets/114665933/b0722909-8a37-454a-a15b-d2f895cb36d0)
However HistoryForge has two Column 21s, a phantom one called “Institutional Work”:
![IMG_0659](https://github.com/historyforge/historyforge/assets/114665933/15263148-a54a-4e8a-8fa0-93dc72c78cf9)
![IMG_0658](https://github.com/historyforge/historyforge/assets/114665933/5d4f2ba3-e7c7-465e-a209-9ff1795c1d35)
Column 22, Public Emergency Work, is fine.

**Comment by PatientRowan** [comment]
Institutional Work also appears on the Fields list, to be deleted there too:
![IMG_0660](https://github.com/historyforge/historyforge/assets/114665933/7d26305a-68d6-4a6a-b0bb-e1a0c0eaacf5)

**Comment by EveSnyder** [comment]
Hi Dave, Could you remove "Institutional Work" from the data entry page and the fields list, it's a mistake and shouldn't be there and its throwing new volunteers for Walnut Hills who are doing the 1940 census.The real Col 21 on the census is private/nonemergency govt work.

**Comment by PatientRowan** [comment]
Thanks, it's looking right to me.  @EveSnyder I think you can let Walnut Hills know.
