### ISSUE TITLE
Limit the census (and other?) databases by locality

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#331]
Can we limit the databases to locality? For example, if the locality filter was set to Groton, and a user then selected Data they wouldn't see anything because we don't have anything for Groton. In the case of Dryden, where we have some Eds in the 1940 and 1950 censuses, they'd see whatever we have from there-likely just the 1940 and 1950 census databases and person database since we haven't "housed" anyone in Dryden.

**Comment by dfurber** [comment]
I think this issue may be obsolete. When I select "Dryden" from the top menu and go to 1940 US Census, I only see records from Dryden.
