### ISSUE TITLE
Walnut Hills HF-new locality added-does not show up on census data entry pages

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#333]
The project coordinator added the locality "East End" recently and its lat/long. She was able to change the building record to that locality but not the person record-you can click East End and save but when you edit the person record they're back in Walnut Hills. I checked the census record (since that's the only census for that person)and the locality dropdown only shows Walnut Hills.

**Comment by dfurber** [comment]
This problem of "locality doesn't show up after you add it" has been a persistent issue over the years. But the fact that she was able to change the building record was a clue. Hopefully I fixed it - but we won't know until somebody adds a new locality and then tries to do something with it right away.
