### ISSUE TITLE
Generate Name Variants From Census Records When a Match Has Been Made

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#336]
On the 1860 census, a family appears enumerated as "Kenady."  Many of their family members appear in directories and later HistoryForge records as Kennedy.  Kennedy is the preferred name.

Young Timothy Kennedy did not (yet) have a HistoryForge appearance.  The steps for his person record: Click on the Create New Person Record button from Timothy Kenady as on the census record.  Click open the resulting person record.  Edit the preferred name field from Kenady to Kennedy.  Save.  The name variant Kenady is automatically snarfed from the census record and put in a name variant field.

[Edited to: the variant Kenady is NOT snarfed from the census record; the computer remembers the original preferred name and retains it as a variant.]

![Screen Shot 2024-04-23 at 7 59 21 AM](https://github.com/historyforge/historyforge/assets/114665933/8c413f44-332f-4800-9125-c26bc4b9aecc)

However, Timothy's mother Ann does have later HistoryForge appearances.  The algorithm offers Ann Kennedy as a match, and you click on the Match! button.  But the Kenady variant is not automatically generated.  You have to add it manually:
  
![Screen Shot 2024-04-23 at 8 04 55 AM](https://github.com/historyforge/historyforge/assets/114665933/71fac10b-656d-4751-992e-9460016050ba)

**Comment by PatientRowan** [comment]
How bad would it be if we generated those kind of name variants automatically?
We'd always have to evaluate the resulting name variant array and make adjustments.
Is it hard to program?  Is it unsafe?  I do not object to the work, but I am writing person record manuals and it's definitely hard to explain.

**Comment by dfurber** [comment]
It was supposed to be doing this all along, but alas there was a bug.

**Comment by PatientRowan** [comment]
This is exciting!  I undid a xref I had made this morning, took off the Person ID from the census record, and hit match all over--and my xref was supplied automatically!  Beautiful.
