### ISSUE TITLE
A way to differentiate buildings at the same address in building dropdown menu

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#34]
For example, 320 N Tioga St  was a house that was knocked down for the courthouse also numbered 320 N Tioga. I have  made two separate buildings on HF to differentiate the buildings that existed there but in the future if someone goes to enter a family at 320 N Tioga St (say for the 1880 census) they will see two buildings at this address listed in the dropdown menu and will likely pick one randomly without further investigation potentially attaching the people to the wrong building.  I have tried different variations of building identification using the building name for CU buildings which didn't necessarily have addresses early on.  For example placing Sage Hall in the house number field, but in that case there was no house number.  We could handle this by entering Courthouse in the house number field and placing the full street address (since its known) in the description field or elsewhere.  I'm not sure how well this will generalize overall to Ithaca and elsewhere though.

**Comment by dfurber** [comment]
I added the building name to the dropdown if it is a "proper name".
