### ISSUE TITLE
Description text box in building and person records

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#341]
We need a way to provide more structure to the Description field of the building and person records, one that will provide
differentiation between the information that it contains, possibly a text box with a field for the source name.
For example: 
<img width="865" alt="Untitled1" src="https://github.com/historyforge/historyforge/assets/57808782/c3ef0af3-5d04-42cc-ba44-b74361fbd423">
<img width="863" alt="Untitled2" src="https://github.com/historyforge/historyforge/assets/57808782/2c9d49e0-90a2-4e3a-8e47-d0782f4057d8">

**Comment by dfurber** [comment]
Closing because source narratives serve this purpose.
