### ISSUE TITLE
“We’re sorry, but something went wrong (500)”

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#344]
Copying @EveSnyder 
Congratulations on Audio Recordings and Videos!  
Probably unrelated, but this morning when I save records, I cannot then re-open some of them—apparently at random.
I’m working on 1850, Page 6.  I get a Sorry message when I try to open newly input records.  Once one of them is hung up, they don’t come back.  However the more I click on ones that were OK, the more then get hung up.  So I won’t give you a complete list.

Samples:
Simpson, Joushua [yes I need to fix that typo]
Grant, Betsey A
Seely, Alanson
Seely, Sophia

**Comment by PatientRowan** [comment]
Whatever this was—if indeed it was anything—we did a whole transcription session on Saturday with no problems for anyone.  I’m closing the issue.

**Comment by dfurber** [comment]
It was something and I fixed it and figured I would hear more if the fix didn't take.

**Comment by PatientRowan** [comment]
Thank you Dave!
