### ISSUE TITLE
adding video and audio

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#345]
I was able to add a video and audio to a building record, but not to a person record.
In the video (and audio)upload sequence, step 6, says "You can date this photo down to" but should say video.
<img width="723" alt="Untitled1" src="https://github.com/historyforge/historyforge/assets/57808782/af15650a-e2ff-4623-b26e-35a588700dae">

From the building record it let me attach it the video to a person record but when I went to check the person record, the video was not there.

From the person record it only let's you add photos, not the other options.

**Comment by dfurber** [comment]
Good point. Please check now!

**Comment by EveSnyder** [comment]
I checked it and its good now. Also I added the audio to a person record for good measure but did not mark the audio record reviewed (because it's not related). When I went to click on the person record to see if it took I got the we're sorry something went wrong message.
