### ISSUE TITLE
weird problem with housing two records

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#35]
For some reason I can't get the building dropdown menu to work for these two records.  
https://www.historyforge.net/census/1940/19012
https://www.historyforge.net/census/1940/19013
The address on the census is 700 Stewart Ave but the address for Belleayre Apartments is 700-702 Stewart Ave.  I tried changing the address to that in one of the census records and it still didn't work.  I also pulled up a new census record and tried adding a completely different address and the building dropdown menu worked, so it seems specific to these records.  Other people in the 1940 census are attached to the building.

**Comment by dfurber** [comment]
I thought it was the hyphen but it wasn't. It was the even hundred on the address. Fix is on the way up.

**Comment by dfurber** [comment]
Too explain, it was translating "700" to searching for address between "700" and "699" instead of "700" and "799".

**Comment by EveSnyder** [comment]
Ah, interesting, thanks. We don't get too many buildings with the even hundred but I have seen a few.
