### ISSUE TITLE
User generated content-no way to add source/narratives on building records when not logged in

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#351]

**Comment by dfurber** [comment]
Correct you have to create an account first. But public can do that now. Don't want the public to add stuff without letting g us know who they are and confirming their email address.

**Comment by EveSnyder** [comment]
The Kresge building https://tompkins.historyforge.net/buildings/7723 has a button to "add source/narrative" under Description.  But if you go to 330 S Cayuga St: https://tompkins.historyforge.net/buildings/1668
There's no "add source/narrative" button-possibly because there's no Description section which, as of now, only appears when someone from the project adds text to that section of the building record.

**Comment by EveSnyder** [comment]
Use 328 S Cayuga instead: https://tompkins.historyforge.net/buildings/2743

**Comment by dfurber** [comment]
Now I get it, and I fixed it, by separating "description" from "sources & narratives". Ideally we can gradually move the descriptions into sources and narratives.

**Comment by PatientRowan** [comment]
A word about "gradually moving descriptions into sources and narratives."   I can adapt to anything, but I currently lean towards keeping both Description and Source/Narrative, with differently defined purposes.  Our person records started as a traditional authority file, and we still need authority file kinds of functions.  I would like to keep the Description field for quick hits that aid in the identification of the person: usually verified birth years, preferred forms of the name, and relatives.  Here is an example from yesterday, when I came across a single person record conflating two Robert Whipples, which I split into two person records:
![Screen Shot 2024-07-23 at 7 31 13 AM](https://github.com/user-attachments/assets/d6d057ea-1991-4a7a-b245-2c07685d0646)
![Screen Shot 2024-07-23 at 7 32 09 AM](https://github.com/user-attachments/assets/9ac918bc-bc43-41c8-bb68-036b16fe2ce9)
My working idea is that the Description helps HistoryForge workers like me differentiate quickly between the contenders -- even though they could examine the database for the same information about parents, dates, etc.  The Source/Narrative area would be the place for users to tell the little-known story of this Robert Whipple's career in grocery store management
![image](https://github.com/user-attachments/assets/88a37805-b71d-403a-92ae-667d729162c2)
