### ISSUE TITLE
Can't add source/narrative to a second person

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#355]
I added narrative to Charles Gilbert's record. https://tompkins.historyforge.net/people/11095
I went back in and edited the narrative to add it to his father Gilbert T Garrett's record. I had a hard time getting the person field it to acknowledge that there is a record for Gilbert T Garrett and when it did, it didn't actually save the narrative to his record.

**Comment by dfurber** [comment]
Fixed but forgot to remove the label and close it.
