### ISSUE TITLE
buildings database filters

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#357]
For the main address (at least), can we filter on No. Prefix, Street Name, Suffix? That would make it easier to separate the even from the odd sides of the street in a spreadsheet.

**Comment by dfurber** [comment]
You'll have to be more specific. You can already search street address for `N Tioga St` and that would give you all buildings on N Tioga St.

**Comment by dfurber** [comment]
What you can't currently do is search by block number or even/odd. Maybe that's the request here?

**Comment by EveSnyder** [comment]
Sorry I meant enable fields rather than filter. My goal is to be able to download the address in its individual components/fields: House No., Prefix, Street Name, and Suffix from the building database so I can open it in excel and make a list of all the buildings on one side of N Cayuga St for example. This is possible from the individual census databases where I can enable those fields on HF before downloading the data etc., but not from the buildings database.

**Comment by EveSnyder** [comment]
Thanks, it sort of works. I was able to enable the fields for the house number street prefix, name, and suffix, but the suffix doesn't populate though these records all have suffixes:
<img width="819" alt="Untitled1" src="https://github.com/user-attachments/assets/28443f7a-c4d0-4863-afea-bf25d6603777">
I am also having trouble downloading a csv now so I can sort the houses by even and odd sides of the street-helpful when trying to check the addresses on the odd or even side of a street to compare the map with HF records. When I click the button it sends a file to my downloads but this is as far as it gets and it never fully downloads:
<img width="764" alt="Untitled2" src="https://github.com/user-attachments/assets/dcabab2e-c1d1-4bdd-bab4-84b85e1a12a2">
I even limited it to S Tioga St which only has 51 records (as opposed to all the building records from the city of Ithaca) and the download is still hung up.
