### ISSUE TITLE
Person Record Birth Year Re-Calculates Even If It Is Not "Estimated"

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#358]
Sometimes we know a person's birth year for sure, and record it in the Description with a source.  We also make sure the correct birth year is entered in the Birth Year field and that "Estimated?" is unchecked, since it is not an estimate (... although gravestone death dates can be outright wrong ...)

@EveSnyder and I have been having what look like edit wars because when one of us changes the birth year and unchecks the Estimated? box, we thought that field was then **protected**.  But it isn't.  The next time the person pops up on a census and one of us matches it to the person record, the Match! process automatically changes the birth year again!  As Eve says, we look stupid:
![Screen Shot 2024-06-26 at 9 14 41 AM](https://github.com/historyforge/historyforge/assets/114665933/8490e9e7-480c-4991-ba11-279acc2659a9)
You can see in the metadata that Eve added the Find a Grave citation for Lucy's 1870 census appearance, changed the birth year, and unchecked the Estimated box.  But then when I came along and matched Lucy for her 1860 appearance, the birth year changes back to the estimated year.  Neither Eve nor I made the change in birth year by hand when we made the second or subsequent match.  It's all happening automatically.

![Screen Shot 2024-06-26 at 9 17 18 AM](https://github.com/historyforge/historyforge/assets/114665933/a4913d06-bfa0-4444-b2c8-b83608b346ca)

**Comment by PatientRowan** [comment]
Two more examples.  These ones have been corrected in the HF fields but you can still see the computer jerking the birth year back and forth in the metadata:
![Screen Shot 2024-06-26 at 9 29 02 AM](https://github.com/historyforge/historyforge/assets/114665933/732b2112-1d50-4c82-aa5e-e2395e766b8f)


![Screen Shot 2024-06-26 at 9 30 11 AM](https://github.com/historyforge/historyforge/assets/114665933/292f2c9d-38d0-4d6e-bd8e-80af9343e5d5)

**Comment by dfurber** [comment]
In the code I see that when a person id changes on a census record, it forces both the person it was connected to before, and the person to which it is newly connected, to estimate birth year and POB over again. It wasn't stopping to ask permission.

I made it so that if it's not marked as estimated and there is no POB, to mark it as estimated and estimate it. Likewise for birth year. This should work. LMK if it does not.

**Comment by PatientRowan** [comment]
When you say “It wasn’t stopping to ask permission,” you’re right, that’s exactly what you want it to do: ask permission to estimate only if the Estimated? box is checked, do no estimate if the box is unchecked.  

But then when you say “if it’s **not** marked as estimated … to mark it as estimated and estimate it,” that’s the inverse of what you want.  Right?  Is this just my head messing things up?  I reviewed a sheet of 1860 this morning but there were too few matches for me to observe what the computer was actually doing.

**Comment by dfurber** [comment]
I pushed this out 2 weeks ago, but forgot to remove the label. LMK how it's been going, and re-open as needed.

**Comment by PatientRowan** [comment]
I think it’s looking good.  In recent weeks we have been working on a 1950 EDs consisting predominantly of Ithaca College dormitories in lower Collegetown and young Cornell couples living on Crescent Place—so not much matching going on.  But we have one volunteer working in 1900 Caroline, and I have not seen any problems in those matches.

**Comment by PatientRowan** [comment]
@EveSnyder here is an example from the 1900 Caroline census where Dave's fix to protect the birth year is working:

![Screen Shot 2024-08-05 at 7 36 55 AM](https://github.com/user-attachments/assets/fbc756c9-5b66-41a4-a991-8f750ea5446d)
