### ISSUE TITLE
404 Page Not Found for Photographs off Person Records

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#367]
When you click on a photograph off a person record, seems like you always get a 404 Page Not Found message now.
On Saturday @EveSnyder was demoing this person record with attached photo: [https://tompkins.historyforge.net/people/10578](url). She clicked on Winifred Bailey’s photo and got the 404 error.  I have run into this problem before and thought it could be solved by clicking in the caption area instead of the photo area (or vice versa—I forget).  When Eve opened the same photograph later in the transcription session, we thought that must be the trick.
  But with further messing around yesterday, Eve and I can’t get any photos to open off a person record, no matter what I do.  There’s nothing obvious wrong with the photos when you go in through the Photographs tab, where they open up fine.   It does not matter if the photos are reviewed or unreviewed, or if there are one or many photos attached.  (For an example of many, see the user-contributed photos here [https://tompkins.historyforge.net/people/154085](url) )
I do not have the same 404 problem when I open a photo off a Building record.

**Comment by dfurber** [comment]
I fixed this. Re-open if you disagree.

**Comment by PatientRowan** [comment]
Nice, thank you.
