### ISSUE TITLE
Person Record “Localities” Not Editable

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#368]
Poor Andrew Aagaard Jr gets a lot of random person record test activity.

@EveSnyder discovered that when you add an additional locality by checking off an extra Localities box on a person record, the edit doesn’t take when you save it.  Edits to Race and Sex do stick, but they’re a little different since you only can have one of them and you do need to change them sometimes.
![IMG_0710](https://github.com/user-attachments/assets/0b883439-c8da-4395-98e1-80dbc02746bd)
The manual currently says that you can edit this field on the person record, but that it should be rare.  (Like, I can’t think of why I’d ever bother).  This is not an issue that I feel strongly about—should I just change the language in the manual to say that Localities are generated by the computer and can’t be edited?

**Comment by dfurber** [comment]
I fixed this. Re-open if you disagree.

**Comment by PatientRowan** [comment]
Thanks.  @EveSnyder, for the manual, Dave has made it editable, it works.
