### ISSUE TITLE
locality for documents/resources page-like with map overlays/The Forge

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#372]
Now that we've expanded beyond the city limits our transcriber resources have become a mess. They are currently organized by census but the 1950 census has 4 different categories. Could you add locality ids to the add document form so that we could assign one or more locality to each transcriber resource and transcribers could limit the resources so they only see those related to their locality? This idea comes from the locality id on the map overlays which allows users to limit what they see on The Forge.

**Comment by dfurber** [comment]
Done!
