### ISSUE TITLE
Make [ ] Persons Button Not Working

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#374]
![Screen Shot 2024-08-05 at 7 48 42 AM](https://github.com/user-attachments/assets/27153d2a-d383-4e76-b4b7-ae5872422c40)

![Screen Shot 2024-08-05 at 7 50 05 AM](https://github.com/user-attachments/assets/4e04dc74-6c3a-4429-ae12-b87614fe505c)

**Comment by PatientRowan** [comment]
The Create New Person Record button, to make the records one-by-one, is also not working this morning.

![Screen Shot 2024-08-05 at 8 03 11 AM](https://github.com/user-attachments/assets/679fa49e-f044-4855-914f-e4092e8e550e)

**Comment by PatientRowan** [comment]
However I was able to match Charles A Babcock this morning.

**Comment by dfurber** [comment]
It's a bit haywire at the moment. Lemme straighten it back out, and then you let me know if stuff is still messed up.

**Comment by PatientRowan** [comment]
No problem.  I have plenty to do without these functions.  Thank you!
