### ISSUE TITLE
Can't review narrative from person record or narrative record

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#376]
If I try to review narratives from the person or narrative record I get a 404 error. 
By narrative record I mean:
<img width="984" alt="Untitled1" src="https://github.com/user-attachments/assets/da897eb0-37b0-4ddc-b396-597d9ee17d60">
I can review a narrative from the building record.

**Comment by dfurber** [comment]
Fixed this earlier in the week.
