### ISSUE TITLE
Census & Person Records for Karanni, B

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#381]
I have screwed this record up so bad.  I apologize to you and to @EveSnyder.
I was playing around with race "Asiatic Indian" versus "Indian" and beefed up the person record for B Karanni (preferred name Bhawan T Karnani) to show that he is from India.  The problem may have started when I decided to generate a new person record (to get Asiatic Indian onto the person record, since it is not a check-off box) but had not deleted the old one yet (which I didn't want to do in case I lost my notes) - ?

Click on Karanni's census record and you get the We're Sorry, Check Logs message:
![Screen Shot 2024-09-12 at 9 43 21 AM](https://github.com/user-attachments/assets/fb44ea54-843d-4c20-897a-51454d88f980)
And notice how his person record does not have any attached census records:
![Screen Shot 2024-09-12 at 9 47 38 AM](https://github.com/user-attachments/assets/0733c865-61c3-46fd-93b4-651bde74240c)

FYI the other guy I was editing is Abdul K. Azad, a roommate of Karnani's, and I didn't screw him up as bad except for whatever is going on with Asiatic Indian.

**Comment by dfurber** [comment]
I got an error email about this and just fixed it. The baby Karnani doesn't have a race on his person record, and I just added that to the display, which made it angry.

**Comment by PatientRowan** [comment]
thank you for saving my bacon Dave.
@EveSnyder , over to you, I’ll work through your race comments later with these examples in mind.
