### ISSUE TITLE
SMTP host-adding here so you can look into this further when you get a chance

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#383]
This is what the person at BU Libraries got when they added their gmail SMTP that they use in other web interfaces
in .exampleconfig:

SMTP_HOST="smtp.gmail.com" \
SMTP_PASSWORD="REDACTED" \
SMTP_PORT="587" \
SMTP_USERNAME="redacted@binghamton.edu" \

and it's not working. It generates a "Something went wrong" error for the end user on the website when trying to invite a new user, and the production.log file doesn't have anything that points me in any direction. I'm not positive it's using those settings, seems like it's trying to use local sendmail or something with the " Delivered mail 66f3161af2991_c57231ba5846512@longitude.binghamton.edu" in the log entries below:

[2024-09-24T15:42:18.983686 #808739]  INFO -- : [1bc45975-1f40-4344-890e-8cbdf6f2e557]   Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"mtuttle@binghamton.edu", "login"=>"mtuttle"}, "commit"=>"Send an invitation"}
I, [2024-09-24T15:42:18.985778 #808739]  INFO -- : [1bc45975-1f40-4344-890e-8cbdf6f2e557] Looking for devise/invitations#create template.
I, [2024-09-24T15:42:18.992424 #808739]  INFO -- : [1bc45975-1f40-4344-890e-8cbdf6f2e557]   Rendered devise/mailer/invitation_instructions.html.erb (Duration: 0.5ms | Allocations: 228)
I, [2024-09-24T15:42:18.992762 #808739]  INFO -- : [1bc45975-1f40-4344-890e-8cbdf6f2e557]   Rendered devise/mailer/invitation_instructions.text.erb (Duration: 0.1ms | Allocations: 180)
I, [2024-09-24T15:42:23.997658 #808739]  INFO -- : [1bc45975-1f40-4344-890e-8cbdf6f2e557] Delivered mail 66f3161af2991_c57231ba5846512@longitude.binghamton.edu.mail (5004.2ms)
I, [2024-09-24T15:42:23.997832 #808739]  INFO -- : [1bc45975-1f40-4344-890e-8cbdf6f2e557] Completed 500 Internal Server Error in 5014ms (ActiveRecord: 2.0ms | Allocations: 7719)
F, [2024-09-24T15:42:23.998624 #808739] FATAL -- : [1bc45975-1f40-4344-890e-8cbdf6f2e557]
[1bc45975-1f40-4344-890e-8cbdf6f2e557] Net::ReadTimeout (Net::ReadTimeout with #<Socket:(closed)>):

**Comment by dfurber** [comment]
```
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    address: ENV['SMTP_HOST'],
    port: ENV['SMTP_PORT'],
    user_name: ENV['SMTP_USERNAME'],
    password: ENV['SMTP_PASSWORD']
  }
```

It is using SMTP settings from ENV vars. However gmail does require some extra settings. I just updated the above code block to include them if the host is `smtp.gmail.com`.

```
smtp_settings = {
    address: ENV['SMTP_HOST'],
    port: ENV['SMTP_PORT'],
    user_name: ENV['SMTP_USERNAME'],
    password: ENV['SMTP_PASSWORD']
  }

  if ENV['SMTP_HOST'].present? && ENV['SMTP_PORT'] == 'smtp.gmail.com'
    smtp_settings.merge!(
      authentication: "plain",
      enable_starttls: true,
      open_timeout: 5,
      read_timeout: 5
    )
  end

  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = smtp_settings
```
