### ISSUE TITLE
Locality Filter not working on all census years

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#386]
If I'm remembering right, the Locality filter used to allow you to use a checkbox to select one of the official Localities--City of Ithaca, etc.?  There is currently no way to ask for a locality:
![Screen Shot 2024-10-28 at 9 30 04 AM](https://github.com/user-attachments/assets/b26578a6-66cf-4c5f-911b-f43b40745167)
You can mostly get around this by asking for Place, but we all know how hinky that can be:

![Screen Shot 2024-10-28 at 9 30 46 AM](https://github.com/user-attachments/assets/659bdd1e-16ca-41e0-834a-cba4cd527a34)

**Comment by EveSnyder** [comment]
Sarah, you can ask for locality in the localities dropdown on the menubar/navbar across the top, so do we want locality to be a filter option as well?

**Comment by PatientRowan** [comment]
I have been paranoid about using the Localities drop-down because (for reviewing) I usually want All and I’m afraid I will forget that I have a locality on.  But yes, I could get used to using it.
—If Locality is offered in the filter area, it should work.
—I think it’s odd to offer every other field as a filter except Locality.  You don’t have to be logged into the system to search with Localities or filters.  I think offering the redundancy of searches is a good idea for members of the public, who may or may not be aware of all the places they can limit by locality.

**Comment by dfurber** [comment]
I brought the choices back. Sorry they went AWOL.
