### ISSUE TITLE
Using locality on the menubar doesn't limit downloads of the 1950 census

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#387]
I had City of Ithaca selected from the Localities dropdown menu but when I downloaded a csv for the 1950 census it gave me all 1950 census records and not just those in the City of Ithaca.

**Comment by EveSnyder** [comment]
I tried limiting it by Place and the download still includes all 1950 census records entered-Caroline, Dryden, Town of Ithaca, Ulysses.

**Comment by EveSnyder** [comment]
Could this be the same problem as issue 391?

**Comment by dfurber** [comment]
The problem here was that the way it keeps track of what locality you selected was no longer in scope when it ran the query for the CSV results. The fix is going out now.

**Comment by dfurber** [comment]
> Could this be the same problem as issue 391?

Yes it is exactly the same problem!
