### ISSUE TITLE
Localities dropdown menus display order

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#388]
Could installations reorder their localities, perhaps using the weighting system used for source/narratives? For example, Tompkins HF has Caroline and Danby at the bottom of the list, We don't want it strictly alphabetical since City of Ithaca is used the most, but at the same time, it doesn't make sense to have the rest alphabetical except for those two. I can see other installations having similar needs in the future.

**Comment by dfurber** [comment]
Go to edit localities, you'll see how you can now rearrange them.

**Comment by EveSnyder** [comment]
Woo hoo! Thanks so much, this will make for better screenshots on the final report.
