### ISSUE TITLE
Binghamton HF contact page missing the contact form

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#393]
From the Binghamton HF team:
There doesn't seem to be any info behind the {{contact_form}} value - so probably something we're missing on the backend/source files. Jesse said it could be because of the way we had to do our install since we don't use Ubuntu here that somehow some file never made it through (?)
Contact page:
![image-2](https://github.com/user-attachments/assets/3975f48c-db5c-489e-9075-8b13f337afd6)
Edited contact form page:
![image](https://github.com/user-attachments/assets/7e59d4ac-fa08-4191-a775-8d43fbfa56fb)

**Comment by dfurber** [comment]
The contact form lives at `/contact` path. It only shows up when you view it at that path. My guess is they clicked "Edit this page", and then "Save and View", which takes you to a view that unfortunately doesn't fill in the contact_form token.

**Comment by dfurber** [comment]
Therefore please confirm that they are looking at /contact, and not at a URL with /cms/pages in it.
