### ISSUE TITLE
Unable to create HF account for adding user-generated content

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#398]
Didn't there used to be a button to click to finish creating a HF account (for user-generated content)? It seems to have disappeared: 
<img width="1177" alt="HF account" src="https://github.com/user-attachments/assets/76ef708e-b561-489d-99bf-892b01a071bb">
I tried to create an account on Schenectady HF after learning that they weren't able to but it didn't work for me either. After entering everything the only option is to click Log In, so I tried that but I didn't get the confirmation instructions in my email so when I selected Didn't receive confirmation instructions and then added my email it gave me the error message that my email wasn't found.
There is a button to click after adding your email to have HF resend confirmation instructions.
<img width="1176" alt="HF account resend confirmation" src="https://github.com/user-attachments/assets/aa3bf60d-8d04-43cd-9e42-0238db7557ee">

**Comment by dfurber** [comment]
Not well documented, but this is tied to Recaptcha. If you pass the Recaptcha human check, then it shows the submit button. If it's not showing at all, it most likely indicates that Recaptcha isn't configured correctly. I'll look into it.

**Comment by EveSnyder** [comment]
Thanks it seems to be working on all site now!
