### ISSUE TITLE
Problem loading person records on SELA HF

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#399]
<img width="1000" alt="Untitled1" src="https://github.com/user-attachments/assets/70e3d0ef-974f-4fc0-9e2f-c5ba7b10f64f">
Note it says 10 record but there are only 9 listed. The same problem happens when I remove the filter on that locality. They were initially adding person records manually for enslaved persons who did not have a last name. I suggested they add the X for last name but it didn't fix the problem. I had a slightly different problem when I tried to add a person record without a last name on Tompkins HF. In that case the record got lost and would not come up when I searched on that first name. When I was able to find it I added a fake last name. The last name issue may not be causing this, but just in case.

**Comment by EveSnyder** [comment]
I just noticed a similar issue #385 from October.

**Comment by EveSnyder** [comment]
Okay I just got additional information. They were experimenting with using source/narrative to link person records to the building record for St. Thomas Cemetery when this happened.
St. Thomas Cemetery: https://sela.historyforge.net/buildings/622
Each source/narrative looks redundant but when you edit it, you can see that it's attached to a person record as well. 
I can't send you a link to the narratives to show you that way because when I click Narratives under Admin on SELA HF I get the "we're sorry something went wrong" message.

**Comment by dfurber** [comment]
I found and fixed the "something went wrong" on the admin narratives page.

I think the first name last name was indeed the issue. I "fixed" it by making them required for person records, along with race and sex. These should have been required a long time ago.

As far as St Thomas Cemetery, it looks like they are trying to document what page in the burial records in which each person is found, as a separate link between that person and that "building". I think what may disambiguate each "source/narrative" is to add the person record link.
