### ISSUE TITLE
The target button on The Forge isn't working

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#400]
When I enable location settings on my phone, go to The Forge page and click the Target button I get this:
![The Forge with target button clicked](https://github.com/user-attachments/assets/094caf8e-59c8-48c7-97c9-19e99d147f70)

**Comment by dfurber** [comment]
I think I found the problem. It still takes a second for the map to load at that zoom level. The problem was that at that zoom level, the "map clusterer" doesn't do clustering. Thus it was rendering thousands of buildings without clusters. I rewrote it so that it only renders the markers that are present on the map that you see. This should speed things up in general. You will notice, however, that when you drag the map, it won't show you new markers until you stop dragging it. Kind of like when you're search on AirBnb or Expedia and you have "search this area" turned on.

**Comment by dfurber** [comment]
I also found that if you add filters to the forge, and then reset, and then refresh, the filters come back. I fixed that too.

**Comment by EveSnyder** [comment]
Thanks, I tried it a few times and each time it loads very slowly and shows this image for a while (at least on my phone-looks like the 1940 map) which makes it seem like it isn't working. The first time I did it I closed it out after a bit but the second time I left it open and put the phone down and when I looked again I could see that it eventually loaded. 
![HistoryForge  HistoryForge](https://github.com/user-attachments/assets/0f39194a-56c8-4e59-ba00-7ea1add6db9f)

**Comment by EveSnyder** [comment]
Also thanks so much, this will allow me to include screenshots of how this works for the final report.

**Comment by dfurber** [comment]
I'm not sure there's much I can do about that, perhaps make it not zoom in quite so far. That's what's going on. The big change in zoom level makes it show the current tiles all zoomed in a blurry while it loads the zoomed in version of the tiles. Everything stops and waits while it does that.

**Comment by dfurber** [comment]
Or I could just make it center the map on your location without zooming. Less of a dramatic effect but won't hit performance.

**Comment by dfurber** [comment]
Try it now please. I made a change that seems to have made it faster, for me anyway.

**Comment by EveSnyder** [comment]
That  works!!!

Eve Snyder, PhD
Historian and Project Director, HistoryForge
<https://tompkins.historyforge.net/>
*The History Center in Tompkins County  <http://thehistorycenter.net/>*
110 North Tioga Street
in the Tompkins Center for History & Culture
Ithaca, NY 14850

Follow HistoryForge on social media:
Facebook: *https://www.facebook.com/ExploreHistoryForge/
<https://www.facebook.com/ExploreHistoryForge/>*
LinkedIn: https://www.linkedin.com/showcase/historyforge


<https://www.facebook.com/tompkinshistory>
<https://twitter.com/TompkinsHistory>
<https://www.instagram.com/tompkinshistory/>
<https://www.youtube.com/channel/UCO-0oMlJzAm0Xb8zYx5az4w>
<https://www.linkedin.com/company/tompkins-history>   @tompkinshistory
