### ISSUE TITLE
SELA HF map overlays missing

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#401]
This is a message I received from SELA HF November 8th at 1:53 pm. At the time it reset itself within a few hours. I received a  message at 12:42 pm today that the same thing happened and by the time I checked about an hour later it was back to normal. Could you check the logs to see if something happened?
 
"SELA HF lost some overlays on the website - it looks like it might have reset to an earlier date. I'm not only missing maps, but I'm also seeing stuff up that I deleted. 
I am specifically missing the Mississippi River COmmission 1886, and two volumes of the 1885-87 Sanborn map series."

**Comment by dfurber** [comment]
My guess is that they had a different locality selected than what they thought. What is described would accord with being scoped to Orleans Parish or all localities.
