### ISSUE TITLE
Transcribers Corner

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#43]
Could you rename it Transcriber's Corner on the dropdown menu-instead of For Transcribers?

Also, could this be reorganized so that it could host the info for all the census years in chronological order.

**Comment by EveSnyder** [comment]
This looks the same as it did before.

**Comment by dfurber** [comment]
That's because I forgot to do the reorg thing.

**Comment by dfurber** [comment]
Now it's done

**Comment by EveSnyder** [comment]
Thanks!
