### ISSUE TITLE
1880 help text for relation to head

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#45]
The enumerators did not enter the term "head" for the head of the family in this census year.  It was the first year they asked this question and the enumerators took the instructions on the census sheet literally, leaving the field blank instead of entering Head: “Relationship of each person to the head of this family—whether wife, son, daughter, servant, border, or other.” 

We want transcribers to enter the word Head. Can you change the help text to this (only for 1880):
Enter what you see on the census. If this field is blank but the person is the Head (the first person with a new dwelling and/or family number), enter the word **Head**.  If the field is blank and the person is not the Head, enter the word **Blank** so you can save the record.  Note: This field has a controlled vocabulary. If, as you enter the term from the census, it does not appear from the list of controlled vocabulary, enter an X in the field and enter “Relation to head is ____” in the notes field.

**Comment by dfurber** [comment]
Done!
