### ISSUE TITLE
Add "groups" concept for users

### ISSUE THREAD

**Issue by dfurber** [historyforge/historyforge#46]
Users can belong to a group. Admins can assign users to the group. Users page has a groups filter.

The rationale is that there are a lot of user accounts prefaced by CU and IC, which clearly mean "Cornell University" and "Ithaca College". It is a case of "when the users make their own field by manipulating another field, you should add the new field".

**Comment by jass2** [comment]
Could a group live as a role, but with no additional permissions?

**Comment by dfurber** [comment]
Two reasons:
1. Roles now live in code rather than database, using a bitmask attribute. So adding a role in the app code that only applies to one HF instance doesn't make sense.
2. Is it any less hacky than what they were already doing? In the sense of leveraging an unrelated feature to achieve a different outcome.

**Comment by dfurber** [comment]
See the new User Groups item on the admin menu.
