### ISSUE TITLE
Duplicates-1940

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#54]
Could you add an administrative override so project coordinators could approve duplicate entries to be entered?  Sometimes enumerators entered the same people twice and the clerks didn't catch it and cross them out.  I think we need to enter them in those cases.

**Comment by dfurber** [comment]
I thought that I removed that governor because of that guy on Tioga St that started the day at his parents house but then came home for dinner, and got counted twice. (OTOH not sure value of entering them twice...)

**Comment by dfurber** [comment]
I think allow multiple census records per year to be connected to the same person record, and enforce unique name/age/address and unique locality/ward/sheet/side/line. So this should be good to go.
