### ISSUE TITLE
Auto select matching building on census record entry

### ISSUE THREAD

**Issue by dfurber** [historyforge/historyforge#63]
If the building autocomplete has a single exact match on address, then use it, instead of the dropdown that can be confusing. And only show dropdown if there are multiple exact matches - which would only be a succession of buildings at the same address.

**Comment by dfurber** [comment]
@EveSnyder I changed the functionality a bit to make it hopefully less maddening. It will only fill in the building list when you've got the house number, street, and suffix. It will only send back exact matches. If there is only one, it will automatically select it. If there are multiple houses with the same exact address, you get to pick. Also if a building is selected, it will hide the "add building" checkbox.

**Comment by EveSnyder** [comment]
Sorry I don't remember your initial comment from October. Does this mean when a transcriber enters the address the list on the building dropdown menu is supposed to only return that exact building and automatically select it if there is only one or let you pick from houses at the same exact address? That isn't happening but it sounds amazing. Also, if there are multiple buildings at the same address, they no longer show things like building name to help differentiate the buildings. It did at one time but I haven't seen that in a while. For example 320 N Tioga St was a residence and then after that was knocked down became the address for the Courthouse. If I type that address in to a data entry page for the 1950 census 320 N Tioga St appears twice in the building dropdown list with no differentiation between the two.  In that case factoring in the year built/year demolished could help remove the building that no longer existed, but we don't always know that or the build date so we don't always enter it in the building record.
