### ISSUE TITLE
Building address change 

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#66]
Would it be possible to make it easier to enter the alternative/historic address. So for example if the only difference was the house number, could we just enter the house number and not have to enter the street name prefix and suffix and the city. Or if the only difference was the street name, etc.  It isn't a big deal when entering all the address info once, but when documenting street name and numbering changes, there are usually a lot of buildings to enter new addresses for and that would make it much easier.

**Comment by dfurber** [comment]
It's tricky because it's hard to know if it is supposed to be blank, or whether it should auto-fill.

**Comment by EveSnyder** [comment]
In the building records would it be possible to add a checkbox after each additional address to auto-fill from the main address the street address (including prefix and suffix but not house number) and the city? 
For now we don't have a lot of cases where the city limits changed but I suppose we should think about that and whether to include that with the street address or separate it out.

**Comment by dfurber** [comment]
I made it so the next address will be the last address minus the house number.
