### ISSUE TITLE
Buildings that go from a single street number to two street numbers between census years

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#68]
I'm not sure how to handle this but there are some buildings that according to the maps are single family homes with one street number in the 1880 Census that were turned into duplexes with two main doors and two street numbers in the 1900 census and after. For example, 53 Prospect in 1880 became 215 and 217 Prospect.  Should I attach the old address of 53 Prospect to both 215 Prospect and 217 Prospect St  or will there be unintended consequences?

**Comment by EveSnyder** [comment]
Actually I had already done that for some building records and the problem is that for the people records in the 1880 census you then have to chose between which building to house them in 53 Prospect St/215 Prospect St or 53 Prospect St/217 Prospect St. I'm not sure if they should be housed in both or how to best handle this on your or my end. I'll leave people like this unhoused for now.

**Comment by dfurber** [comment]
I see that 215 and 217 both have 53 Prospect as an historical address, and it looks fine, no?

**Comment by EveSnyder** [comment]
Only 215 Prospect St has the residents from the 1880 census, shouldn't they be in both under 1880 since it was the same building?
215-https://www.historyforge.net/buildings/2227
217-https://www.historyforge.net/buildings/2226

**Comment by dfurber** [comment]
A census record can only belong to one building.

**Comment by dfurber** [comment]
I think you did right to pick the lower numbered address be the "original" one. The only thing I can think of is to add a "parent building" concept to building record. If you say that 215 Prospect is a parent of 217, then I could show 215's residents in 217 for the census before it hived off.

**Comment by dfurber** [comment]
For "parent building" you'd have to enter a building ID and a "hive" year.

**Comment by dfurber** [comment]
And I did it. If you look at 217 Prospect St (https://tompkins.historyforge.net/buildings/2226), you'll see that it split from 215 Prospect St by 1910. And 215's residents from 1880 and 1900 will show on 217.
