### ISSUE TITLE
remove New York from parents POB in the fields for non-supplemental records

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#76]
Would it be possible for you to write a script that removed the unnecessary NYs in the supplemental record for EDs 21-24 where the other supplemental fields are blank?  There will still be approx 2 lines per sheet that are supposed to have parents POBs and other supplemental fields.

**Comment by dfurber** [comment]
I just did - you will have to check yourself for the ones where the line is 14 or 29.

**Comment by dfurber** [comment]
That is to say, I made it find everyone with pob mother and father of "New York" in those enum districts, not on line 14 or 29, in which the usual occupation was "". That seemed to leave out apparent false positives.
