### ISSUE TITLE
"As of" year for testing partners

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#83]
Could you add the "as of" year for testing partners-and let me know when you do so I can let them know to start using it if they need it-which some do.

**Comment by dfurber** [comment]
If you haven't figured it out on your own yet, it's part of the locality. See here: https://ithaca.historyforge.net/localities/1/edit

**Comment by EveSnyder** [comment]
Okay, that's for blanket changes for the whole city and at this point, I don't know how that works as part of the larger system since I've been adding the as of years to all the records as it becomes necessary.  I didn't know you had already added the as of year there or in the building records themselves. I'll let the testing partners know about both.
