### ISSUE TITLE
Unable to correctly "House" several census records

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#88]
We tried to "house" two records for 204 N Aurora St in the 1880 census and the building dropdown menu returns unrelated addresses on Auburn St
https://www.historyforge.net/census/1880/8042
https://www.historyforge.net/census/1880/8043
There is a building record for 204 N Aurora which is 842 N Aurora after 1899 and it appears that everything has been entered correctly-https://www.historyforge.net/buildings/3470
There are similar issues for census records at 208, 212, 225, 229, 235, 236, and 245. Here again I checked the building records and there don't seem to be any typos or other reasons that I can tell as to why this isn't working for these records.

**Comment by dfurber** [comment]
Is this still a problem? When I go to those records, I don't see Auburn St in the dropdown.

**Comment by EveSnyder** [comment]
Obviously not still a problem, however, if you look at the building dropdown menu in that record it lists the buildings in this order
200 N Aurora St
25 N Aurora St
26 N Aurora St
202 N Aurora St 
204 N Aurora St
26 N Aurora St
etc.
Can the field be limited to where it lists the two digit numbers first and then the three digit numbers after it hits 99? Transcribers will be confused by this which could result in them housing people in the wrong buildings.
