### ISSUE TITLE
Beef up user management page

### ISSUE THREAD

**Issue by dfurber** [historyforge/historyforge#9]
Should be able to search user name, role, the usual stuff. The search should be accomplished using Ransack rather than constructed by hand in the controller, as it is currently. Outcome: the view uses Ransack scopes and sort_links; the controller creates a ransack search and runs the search.

**Comment by jass2** [comment]
Is this still a good place to pick up?

**Comment by dfurber** [comment]
Yes it is. It's not very sexy but needs to be done before opening user registration to the public.

**Comment by jass2** [comment]
I've configured searching by assigned role! It already appears we can search by username, did you mean to search by other attributes currently in the user table?

**Comment by dfurber** [comment]
Yes - particularly by role.

**Comment by dfurber** [comment]
Oh and welcome to the party! It's great to see your contribution. Thank you!
